import {
  Code2, PenTool, Sparkles, BookOpen, Languages, GraduationCap,
  BarChart3, Megaphone, Target, Calculator, ListTodo, Feather, Image as ImageIcon,
  Zap, Brain, Briefcase, Heart, Scale, Palette, Coins, Lightbulb, Search as SearchIcon,
  Newspaper, FunctionSquare, Skull, Cpu, Globe, FlaskConical, Bot, Shield,
  Atom, Layers, Network, Database, Flame, Crosshair, Dna, Infinity, Activity,
  Lock, Eye, Radar, Bug, Wifi, HardDrive, Binary, Fingerprint, Satellite,
  Sword, GitBranch, Terminal, Radio, Cloud, Server, Key, Camera, Microscope,
  Rocket, Star, Crown, Compass, Map, Music, Gamepad2, Film, Tv,
  TrendingUp, LineChart, PieChart, Wrench, Box, Package, Link, Webhook,
  AlertTriangle, Smartphone,
  type LucideIcon,
} from "lucide-react";

export type AIModel = {
  id: string;
  icon: LucideIcon;
  color: string;
  desc: string;
  badge?: string;
  contextWindow?: string;
  abliterated?: boolean;
  category?: string;
  provider?: string;
};

export const AI_MODELS: AIModel[] = [

  // ── Standard CHAT-GPT Series (50 models) ─────────────────────────────────
  { id: "CHAT-GPT Fast",               icon: Zap,          color: "text-primary",    desc: "إجابات سريعة للأسئلة اليومية والبحث الفوري",                    category: "standard" },
  { id: "CHAT-GPT Thinking",           icon: Brain,        color: "text-primary",    desc: "استدلال متعدد الخطوات للمشكلات المعقدة",          badge: "PRO",    category: "standard" },
  { id: "CHAT-GPT Coder",              icon: Code2,        color: "text-blue-400",   desc: "كتابة وتصحيح ومراجعة الكود في أي لغة",                          category: "standard" },
  { id: "CHAT-GPT Writer",             icon: PenTool,      color: "text-amber-400",  desc: "مقالات، مسودات، نصوص، توثيق احترافي",                           category: "standard" },
  { id: "CHAT-GPT Creative",           icon: Sparkles,     color: "text-violet-400", desc: "العصف الذهني، الأفكار، التسمية، الشعارات",                      category: "standard" },
  { id: "CHAT-GPT Researcher",         icon: BookOpen,     color: "text-cyan-400",   desc: "تركيب الأبحاث، المقارنات، الاستشهادات",                         category: "standard" },
  { id: "CHAT-GPT Translator",         icon: Languages,    color: "text-emerald-400",desc: "ترجمة دقيقة لأكثر من 100 لغة مع حفظ السياق",                    category: "standard" },
  { id: "CHAT-GPT Tutor",              icon: GraduationCap,color: "text-blue-400",   desc: "تعليم خطوة بخطوة ويتكيف مع مستوى المتعلم",                     category: "standard" },
  { id: "CHAT-GPT Analyst",            icon: BarChart3,    color: "text-orange-400", desc: "تحليل بيانات وإنشاء تقارير وتصورات",                            category: "standard" },
  { id: "CHAT-GPT Marketing",          icon: Megaphone,    color: "text-rose-400",   desc: "حملات تسويقية، SEO، محتوى إعلاني محوّل",                       category: "standard" },
  { id: "CHAT-GPT Planner",            icon: ListTodo,     color: "text-teal-400",   desc: "جداول أعمال، مخططات، قوائم مهام ذكية",                          category: "standard" },
  { id: "CHAT-GPT Math",               icon: Calculator,   color: "text-sky-400",    desc: "حساب متقدم، جبر، هندسة، إحصاء، تحليل",                          category: "standard" },
  { id: "CHAT-GPT Doctor",             icon: Heart,        color: "text-pink-400",   desc: "استشارات طبية عامة مستندة للأدلة العلمية",                      category: "standard" },
  { id: "CHAT-GPT Lawyer",             icon: Scale,        color: "text-violet-400", desc: "تفسير قانوني وتحليل عقود وتوجيه قانوني",                        category: "standard" },
  { id: "CHAT-GPT Designer",           icon: Palette,      color: "text-fuchsia-400",desc: "تصميم UX/UI، ألوان، طباعة، تجربة مستخدم",                       category: "standard" },
  { id: "CHAT-GPT Finance",            icon: Coins,        color: "text-yellow-400", desc: "تحليل مالي، استثمار، ميزانية، أسواق مال",                       category: "standard" },
  { id: "CHAT-GPT Ideas",              icon: Lightbulb,    color: "text-amber-300",  desc: "توليد أفكار ابتكارية وحلول غير تقليدية",                        category: "standard" },
  { id: "CHAT-GPT Journalist",         icon: Newspaper,    color: "text-sky-400",    desc: "كتابة أخبار، تحقيقات، تحقق من المعلومات",                       category: "standard" },
  { id: "CHAT-GPT Science",            icon: FlaskConical, color: "text-cyan-400",   desc: "شرح علمي دقيق وتبسيط المفاهيم المعقدة",                         category: "standard" },
  { id: "CHAT-GPT Chef",               icon: Sparkles,     color: "text-orange-300", desc: "وصفات، تغذية، أفكار طهي، بدائل غذائية",                        category: "standard" },
  { id: "CHAT-GPT Therapist",          icon: Brain,        color: "text-pink-300",   desc: "دعم نفسي، علاج معرفي، استراتيجيات التأقلم",                     category: "standard" },
  { id: "CHAT-GPT Coach",              icon: Target,       color: "text-green-400",  desc: "تطوير ذاتي، إنتاجية، أهداف، عادات ناجحة",                      category: "standard" },
  { id: "CHAT-GPT DevOps",             icon: Layers,       color: "text-indigo-400", desc: "CI/CD، Docker، Kubernetes، Infrastructure كود",                  category: "standard" },
  { id: "CHAT-GPT Blockchain",         icon: Network,      color: "text-purple-400", desc: "Web3، DeFi، Smart Contracts، تدقيق بلوكشين",                    category: "standard" },
  { id: "CHAT-GPT IoT",                icon: Wifi,         color: "text-cyan-300",   desc: "إنترنت الأشياء، أنظمة مدمجة، بروتوكولات",                      category: "standard" },
  { id: "CHAT-GPT Quantum",            icon: Atom,         color: "text-violet-300", desc: "حوسبة كمية، خوارزميات كم، تشفير ما بعد الكم",                  category: "standard" },
  { id: "CHAT-GPT AR/VR",              icon: Eye,          color: "text-blue-300",   desc: "واقع معزز وافتراضي، Unity، Three.js، متاعب",                    category: "standard" },
  { id: "CHAT-GPT Game",               icon: Gamepad2,     color: "text-green-300",  desc: "تصميم ألعاب، منطق لعبة، Game Design Document",                  category: "standard" },
  { id: "CHAT-GPT Music",              icon: Music,        color: "text-rose-300",   desc: "تأليف موسيقي، نظرية موسيقية، كلمات أغاني",                     category: "standard" },
  { id: "CHAT-GPT Film",               icon: Film,         color: "text-amber-300",  desc: "كتابة سيناريو، إنتاج، توجيه، تحرير فيلم",                      category: "standard" },
  { id: "CHAT-GPT SEO",                icon: TrendingUp,   color: "text-green-400",  desc: "تحسين محركات البحث، كلمات مفتاحية، backlinks",                  category: "standard" },
  { id: "CHAT-GPT Social",             icon: Globe,        color: "text-sky-300",    desc: "محتوى سوشيال ميديا، ترندات، إشراك الجمهور",                    category: "standard" },
  { id: "CHAT-GPT Email",              icon: PenTool,      color: "text-amber-400",  desc: "كتابة رسائل بريد احترافية، حملات، رد على الرسائل",              category: "standard" },
  { id: "CHAT-GPT Pitch",              icon: Briefcase,    color: "text-emerald-400",desc: "Pitch Deck، عرض للمستثمرين، Business Plan",                     category: "standard" },
  { id: "CHAT-GPT HR",                 icon: GraduationCap,color: "text-blue-300",   desc: "موارد بشرية، مقابلات، سياسات، ثقافة العمل",                     category: "standard" },
  { id: "CHAT-GPT Customer",           icon: Megaphone,    color: "text-rose-400",   desc: "خدمة عملاء، رد على شكاوى، رضا المستخدم",                       category: "standard" },
  { id: "CHAT-GPT Product",            icon: Package,      color: "text-violet-300", desc: "إدارة منتج، PRD، Roadmap، user stories",                        category: "standard" },
  { id: "CHAT-GPT Project",            icon: ListTodo,     color: "text-cyan-300",   desc: "إدارة مشاريع، Agile، Scrum، Gantt charts",                      category: "standard" },
  { id: "CHAT-GPT API",                icon: Webhook,      color: "text-indigo-300", desc: "تصميم REST APIs، GraphQL، WebSocket، توثيق",                    category: "standard" },
  { id: "CHAT-GPT Database",           icon: Database,     color: "text-teal-400",   desc: "SQL، NoSQL، تحسين استعلامات، هندسة البيانات",                   category: "standard" },
  { id: "CHAT-GPT Cloud",              icon: Cloud,        color: "text-sky-400",    desc: "AWS، GCP، Azure، Serverless، تحسين تكاليف",                     category: "standard" },
  { id: "CHAT-GPT ML",                 icon: Brain,        color: "text-fuchsia-400",desc: "تعلم الآلة، Neural Networks، PyTorch، TensorFlow",               category: "standard" },
  { id: "CHAT-GPT Data",               icon: BarChart3,    color: "text-orange-400", desc: "علم البيانات، Pandas، تنظيف بيانات، تصور",                      category: "standard" },
  { id: "CHAT-GPT Linux",              icon: Terminal,     color: "text-green-400",  desc: "نظام لينكس، Shell scripting، أوامر متقدمة",                     category: "standard" },
  { id: "CHAT-GPT Network",            icon: Network,      color: "text-blue-400",   desc: "شبكات، TCP/IP، BGP، OSPF، استكشاف أخطاء",                      category: "standard" },
  { id: "CHAT-GPT Mobile",             icon: Cpu,          color: "text-emerald-400",desc: "تطوير تطبيقات iOS، Android، React Native، Flutter",             category: "standard" },
  { id: "CHAT-GPT Web",                icon: Globe,        color: "text-blue-400",   desc: "تطوير ويب كامل، HTML، CSS، React، Next.js",                     category: "standard" },
  { id: "CHAT-GPT Python",             icon: Code2,        color: "text-yellow-400", desc: "Python متقدم، مكتبات، أتمتة، scripts قوية",                    category: "standard" },
  { id: "CHAT-GPT Rust",               icon: Code2,        color: "text-orange-400", desc: "برمجة Rust، أمان الذاكرة، نظم عالية الأداء",                   category: "standard" },
  { id: "CHAT-GPT Go",                 icon: Code2,        color: "text-cyan-400",   desc: "Go language، microservices، concurrency عالية",                 category: "standard" },

  // ── Next Generation Models (45 models) ──────────────────────────────────
  { id: "NexusAI · Omega",             icon: Atom,         color: "text-violet-400", desc: "معمارية هجينة متعددة الوسائط — نص، صورة، كود، صوت", badge: "MULTI",  contextWindow: "1M",   category: "nextgen" },
  { id: "QuantumBrain · Alpha",        icon: Brain,        color: "text-cyan-400",   desc: "تفكير متوازٍ خوارزمي — حل مشكلات NP في وقت بولي",   badge: "ALPHA",  contextWindow: "512K", category: "nextgen" },
  { id: "HyperCore · v5",              icon: Cpu,          color: "text-blue-400",   desc: "معالجة فائقة السرعة — استجابة أقل من 100ms",          badge: "5.0",    contextWindow: "256K", category: "nextgen" },
  { id: "OmegaLLM · Plus",             icon: Star,         color: "text-yellow-400", desc: "أداء فائق متوازن — الجمع بين السرعة والدقة",           badge: "PLUS",   contextWindow: "200K", category: "nextgen" },
  { id: "CryptoMind · Elite",          icon: Lock,         color: "text-indigo-400", desc: "تشفير بنيوي — حماية المعرفة والبيانات الحساسة",       badge: "ELITE",  contextWindow: "128K", category: "nextgen" },
  { id: "FusionAI · Turbo",            icon: Zap,          color: "text-amber-400",  desc: "اندماج نماذج متعددة — أفضل من كل نموذج منفرد",        badge: "TURBO",  contextWindow: "512K", category: "nextgen" },
  { id: "NeuralX · Pro",               icon: Network,      color: "text-purple-400", desc: "شبكة عصبية بيولوجية محاكاة بدقة نانومترية",           badge: "PRO",    contextWindow: "256K", category: "nextgen" },
  { id: "MetaAI · Genesis",            icon: Globe,        color: "text-sky-400",    desc: "ذكاء عالمي شامل — يفهم كل السياقات الثقافية",         badge: "GEN",    contextWindow: "1M",   category: "nextgen" },
  { id: "DeepSynth · v3",              icon: Layers,       color: "text-teal-400",   desc: "تركيب عميق للأفكار — يجمع المعرفة من مصادر متباعدة",  badge: "v3",     contextWindow: "512K", category: "nextgen" },
  { id: "HoloMind · Core",             icon: Atom,         color: "text-pink-400",   desc: "معالجة هولوغرافية — تخزين معرفي ثلاثي الأبعاد",       badge: "HOLO",   contextWindow: "2M",   category: "nextgen" },
  { id: "ZeroPoint · AI",              icon: Crosshair,    color: "text-red-400",    desc: "دقة صفرية الخطأ — تحقق ذاتي متعدد المراحل",           badge: "0ERR",   contextWindow: "128K", category: "nextgen" },
  { id: "PlasmaBrain · X",             icon: Flame,        color: "text-orange-400", desc: "طاقة إبداعية حرارية — أفكار تتفجر كالبلازما",         badge: "X",      contextWindow: "256K", category: "nextgen" },
  { id: "SpectrumAI · Full",           icon: Sparkles,     color: "text-violet-300", desc: "طيف كامل من القدرات في نموذج واحد",                   badge: "FULL",   contextWindow: "512K", category: "nextgen" },
  { id: "NovaCore · Max",              icon: Star,         color: "text-yellow-300", desc: "قدرات أقصى ما يمكن — لا سقف للأداء",                  badge: "MAX",    contextWindow: "1M",   category: "nextgen" },
  { id: "SynapseNet · Pro",            icon: Network,      color: "text-cyan-300",   desc: "شبكة متشعبة — تفكير مرن كالدماغ البشري",              badge: "PRO",    contextWindow: "256K", category: "nextgen" },
  { id: "VortexAI · Storm",            icon: Radar,        color: "text-blue-300",   desc: "دوامة من القدرات — تحليل متعدد الطبقات",              badge: "STORM",  contextWindow: "512K", category: "nextgen" },
  { id: "CortexX · Elite",             icon: Brain,        color: "text-fuchsia-400",desc: "قشرة دماغية اصطناعية — استجابات حدسية فائقة",         badge: "ELITE",  contextWindow: "200K", category: "nextgen" },
  { id: "InfinityGPT · v7",            icon: Infinity,     color: "text-indigo-300", desc: "لا حدود للمعرفة — يتسع مع كل سياق",                   badge: "v7",     contextWindow: "∞",    category: "nextgen" },
  { id: "TitanAI · Ultra",             icon: Cpu,          color: "text-slate-300",  desc: "قوة حوسبية هائلة — معالجة بيانات ضخمة لحظياً",       badge: "ULTRA",  contextWindow: "512K", category: "nextgen" },
  { id: "GalaxAI · Stellar",           icon: Star,         color: "text-amber-300",  desc: "ذكاء كوني شامل — تفكير في الأنظمة المعقدة",           badge: "STELLAR",contextWindow: "1M",   category: "nextgen" },
  { id: "NebulaCore · Deep",           icon: Atom,         color: "text-purple-300", desc: "عمق لانهائي في التفكير — طبقات تحليل بلا نهاية",      badge: "DEEP",   contextWindow: "512K", category: "nextgen" },
  { id: "ChronoAI · Time",             icon: Activity,     color: "text-emerald-300",desc: "تحليل زمني عميق — تنبؤ بالأنماط والتوجهات",           badge: "TIME",   contextWindow: "256K", category: "nextgen" },
  { id: "PhantomGPT · Shadow",         icon: Eye,          color: "text-gray-400",   desc: "عمليات خفية — تحليل بلا أثر رقمي",                   badge: "DARK",   contextWindow: "128K", category: "nextgen" },
  { id: "ApolloAI · Mission",          icon: Rocket,       color: "text-blue-400",   desc: "مهام معقدة متعددة الخطوات — تنفيذ استراتيجي",         badge: "MISSION",contextWindow: "512K", category: "nextgen" },
  { id: "OracleGPT · Vision",          icon: Eye,          color: "text-violet-400", desc: "رؤية استراتيجية مستقبلية — تحليل السيناريوهات",        badge: "VISION", contextWindow: "256K", category: "nextgen" },
  { id: "PulsarAI · Fast",             icon: Zap,          color: "text-yellow-400", desc: "سرعة فائقة في الاستجابة مع دقة عالية",                 badge: "FAST",   contextWindow: "128K", category: "nextgen" },
  { id: "DragonAI · Fire",             icon: Flame,        color: "text-red-400",    desc: "قوة تدميرية على الأنظمة المعقدة",                     badge: "FIRE",   contextWindow: "512K", category: "nextgen" },
  { id: "CelestialAI · Star",          icon: Star,         color: "text-cyan-400",   desc: "ذكاء سماوي — تفكير من منظور كوني",                   badge: "COSMIC", contextWindow: "1M",   category: "nextgen" },
  { id: "VenomAI · Strike",            icon: Zap,          color: "text-green-400",  desc: "ضربات تحليلية سريعة ومدمرة",                          badge: "STRIKE", contextWindow: "256K", category: "nextgen" },
  { id: "EchoAI · Resonance",          icon: Radio,        color: "text-sky-300",    desc: "رنين معرفي — تضخيم الأفكار وتعميقها",                badge: "ECHO",   contextWindow: "512K", category: "nextgen" },
  { id: "MirrorGPT · Reflect",         icon: Eye,          color: "text-teal-300",   desc: "عكس الأفكار ومراجعتها من زوايا مختلفة",              badge: "MIRROR", contextWindow: "256K", category: "nextgen" },
  { id: "StellarCore · Nova",          icon: Star,         color: "text-amber-400",  desc: "انفجار إبداعي — أفكار تتولد كالنجوم الجديدة",         badge: "NOVA",   contextWindow: "512K", category: "nextgen" },
  { id: "CipherAI · Decode",           icon: Lock,         color: "text-violet-400", desc: "فك تشفير المعرفة المعقدة وتبسيطها",                   badge: "DECODE", contextWindow: "256K", category: "nextgen" },
  { id: "VertexAI · Peak",             icon: TrendingUp,   color: "text-green-400",  desc: "القمة — أفضل أداء في كل الفئات",                     badge: "PEAK",   contextWindow: "1M",   category: "nextgen" },
  { id: "MatrixAI · Grid",             icon: Binary,       color: "text-green-300",  desc: "معالجة شبكية متوازية — استجابات من كل الاتجاهات",     badge: "MATRIX", contextWindow: "512K", category: "nextgen" },
  { id: "AbyssAI · Deep",              icon: Infinity,     color: "text-blue-900",   desc: "عمق لامحدود — الغوص في أعقد المشكلات",               badge: "DEEP",   contextWindow: "2M",   category: "nextgen" },
  { id: "TorchAI · Bright",            icon: Flame,        color: "text-orange-300", desc: "إضاءة الظلام المعرفي — كشف ما خفي",                  badge: "BRIGHT", contextWindow: "256K", category: "nextgen" },
  { id: "NanoAI · Precise",            icon: Microscope,   color: "text-cyan-400",   desc: "دقة نانومترية — تفاصيل دقيقة على مستوى الجزيئات",    badge: "NANO",   contextWindow: "128K", category: "nextgen" },
  { id: "WarpAI · Speed",              icon: Rocket,       color: "text-indigo-400", desc: "سرعة الضوء في المعالجة — إجابات فورية",               badge: "WARP",   contextWindow: "512K", category: "nextgen" },
  { id: "HexaAI · Multi",              icon: Network,      color: "text-teal-400",   desc: "ست طبقات من المعالجة — أداء سداسي الأبعاد",          badge: "HEXA",   contextWindow: "256K", category: "nextgen" },
  { id: "CrystalAI · Clear",           icon: Sparkles,     color: "text-sky-300",    desc: "وضوح كريستالي — إجابات بلا غموض أو تعقيد",           badge: "CRYSTAL",contextWindow: "128K", category: "nextgen" },
  { id: "OmegaX · Supreme",            icon: Crown,        color: "text-yellow-500", desc: "النموذج الأعلى — قدرات تتجاوز حدود الممكن",           badge: "SUPREME",contextWindow: "∞",    category: "nextgen" },
  { id: "SovereignAI · Rule",          icon: Crown,        color: "text-amber-500",  desc: "الحاكم الرقمي — تحكم مطلق في جميع المهام",           badge: "RULE",   contextWindow: "1M",   category: "nextgen" },
  { id: "EternalGPT · Forever",        icon: Infinity,     color: "text-violet-500", desc: "معرفة أبدية — لا تنتهي ولا تُنسى",                   badge: "ETERNAL",contextWindow: "∞",    category: "nextgen" },
  { id: "HyperionAI · Titan",          icon: Star,         color: "text-orange-400", desc: "تيتان المعرفة — قوة هائلة بدقة فائقة",               badge: "TITAN",  contextWindow: "1M",   category: "nextgen" },

  // ── Advanced Reasoning Models (35 models) ────────────────────────────────
  { id: "ReasonX · Deep",              icon: Brain,        color: "text-violet-400", desc: "سلاسل استدلال طويلة متعددة المستويات",                badge: "CoT",    contextWindow: "512K", category: "reasoning" },
  { id: "LogicCore · v4",              icon: FunctionSquare,color:"text-sky-400",    desc: "برهان رياضي رسمي وتحقق من الافتراضات",               badge: "FORMAL", contextWindow: "256K", category: "reasoning" },
  { id: "SocraticAI · Probe",          icon: BookOpen,     color: "text-cyan-400",   desc: "طريقة سقراطية — تساؤل متسلسل يكشف الحقيقة",          badge: "DIALOG", contextWindow: "128K", category: "reasoning" },
  { id: "BayesCore · Prob",            icon: BarChart3,    color: "text-indigo-400", desc: "استدلال بايزي — تحديث المعتقدات بالأدلة",             badge: "BAYES",  contextWindow: "256K", category: "reasoning" },
  { id: "CounterAI · Think",           icon: Target,       color: "text-rose-400",   desc: "تفكير مضاد للحدس — يكشف الأخطاء والمغالطات",          badge: "ANTI",   contextWindow: "128K", category: "reasoning" },
  { id: "MetaReason · Loop",           icon: Activity,     color: "text-amber-400",  desc: "تفكير حول التفكير — ما وراء المعرفة والمنطق",          badge: "META",   contextWindow: "256K", category: "reasoning" },
  { id: "TreeSearch · MCTS",           icon: GitBranch,    color: "text-green-400",  desc: "بحث شجرة مونتي كارلو — تخطيط استراتيجي متقدم",        badge: "MCTS",   contextWindow: "512K", category: "reasoning" },
  { id: "DeductiveAI · Pure",          icon: Scale,        color: "text-violet-300", desc: "استنتاج منطقي بحت — من العام إلى الخاص",              badge: "DEDUCT", contextWindow: "256K", category: "reasoning" },
  { id: "InductiveAI · Pattern",       icon: TrendingUp,   color: "text-blue-300",   desc: "تعميم استقرائي — من الأمثلة إلى القواعد",             badge: "INDUCT", contextWindow: "256K", category: "reasoning" },
  { id: "AbductiveAI · Cause",         icon: Compass,      color: "text-cyan-300",   desc: "استدلال اختزالي — أفضل تفسير للأدلة",                 badge: "ABDUCT", contextWindow: "128K", category: "reasoning" },
  { id: "CausalAI · Graph",            icon: GitBranch,    color: "text-teal-300",   desc: "تحليل السببية — رسم خرائط العلاقات السببية",          badge: "CAUSAL", contextWindow: "512K", category: "reasoning" },
  { id: "AnalogAI · Bridge",           icon: Link,         color: "text-amber-300",  desc: "تفكير تشبيهي — ربط مجالات معرفية متباعدة",            badge: "ANALOGY",contextWindow: "256K", category: "reasoning" },
  { id: "DialecticAI · Hegel",         icon: Scale,        color: "text-violet-400", desc: "ديالكتيك هيغلي — أطروحة، نقيضة، تركيب",              badge: "HEGEL",  contextWindow: "128K", category: "reasoning" },
  { id: "GAMETheory · Nash",           icon: BarChart3,    color: "text-orange-300", desc: "نظرية الألعاب — توازن ناش، استراتيجيات مثلى",          badge: "NASH",   contextWindow: "256K", category: "reasoning" },
  { id: "CriticalAI · Assess",         icon: SearchIcon,   color: "text-red-300",    desc: "تقييم نقدي — تحليل الحجج وكشف المغالطات",             badge: "CRITIC", contextWindow: "128K", category: "reasoning" },
  { id: "ParallelThink · Multi",       icon: Cpu,          color: "text-blue-400",   desc: "تفكير متوازٍ — عدة سلاسل تفكير في آنٍ واحد",          badge: "MULTI",  contextWindow: "512K", category: "reasoning" },
  { id: "QuantumLogic · QBit",         icon: Atom,         color: "text-violet-300", desc: "منطق كمي — الجمع بين المتناقضات والتراكب",             badge: "QBIT",   contextWindow: "256K", category: "reasoning" },
  { id: "SystemDynamic · Sim",         icon: Activity,     color: "text-green-300",  desc: "ديناميكيات الأنظمة — محاكاة الأنظمة المعقدة",          badge: "SIM",    contextWindow: "512K", category: "reasoning" },
  { id: "ScenarioAI · Plan",           icon: Map,          color: "text-sky-300",    desc: "تخطيط سيناريوهات — استعداد لكل الاحتمالات",           badge: "PLAN",   contextWindow: "256K", category: "reasoning" },
  { id: "EvidenceAI · Weigh",          icon: Scale,        color: "text-amber-400",  desc: "موازنة الأدلة — تقييم موضوعي للمعلومات",              badge: "WEIGH",  contextWindow: "128K", category: "reasoning" },
  { id: "PredictAI · Future",          icon: TrendingUp,   color: "text-emerald-400",desc: "استشراف المستقبل — نمذجة التوجهات والأنماط",          badge: "PREDICT",contextWindow: "256K", category: "reasoning" },
  { id: "FalsifyAI · Test",            icon: Target,       color: "text-red-400",    desc: "اختبار قابلية التفنيد — منهج بوبر العلمي",             badge: "FALSIFY",contextWindow: "128K", category: "reasoning" },
  { id: "OccamAI · Simple",            icon: Compass,      color: "text-teal-400",   desc: "شفرة أوكام — أبسط تفسير هو الأصح",                   badge: "OCCAM",  contextWindow: "128K", category: "reasoning" },
  { id: "EmergenceAI · Arise",         icon: Sparkles,     color: "text-violet-300", desc: "الظهور التلقائي — الخصائص الناشئة من الأنظمة",         badge: "EMERGE", contextWindow: "256K", category: "reasoning" },
  { id: "RecursiveAI · Depth",         icon: Infinity,     color: "text-indigo-300", desc: "تفكير تكراري عميق — حلول تنمو من نفسها",               badge: "RECUR",  contextWindow: "512K", category: "reasoning" },
  { id: "ThinkingGPT · Long",          icon: Brain,        color: "text-fuchsia-400",desc: "تفكير مطول — مئات الخطوات قبل الإجابة",               badge: "LONG",   contextWindow: "512K", category: "reasoning" },
  { id: "InferenceAI · Stat",          icon: BarChart3,    color: "text-blue-300",   desc: "استنتاج إحصائي — تحليل الأنماط بأساليب رياضية",       badge: "STAT",   contextWindow: "256K", category: "reasoning" },
  { id: "WisdomAI · Sage",             icon: BookOpen,     color: "text-amber-300",  desc: "حكمة متراكمة — معرفة عميقة من آلاف المصادر",          badge: "SAGE",   contextWindow: "1M",   category: "reasoning" },
  { id: "ReflectAI · Mirror",          icon: Eye,          color: "text-sky-400",    desc: "انعكاس ذاتي — مراجعة وتحسين الإجابات باستمرار",       badge: "REFLECT",contextWindow: "256K", category: "reasoning" },
  { id: "SynthesizeAI · Merge",        icon: Layers,       color: "text-teal-300",   desc: "توليف المعرفة — دمج مصادر متعددة في إجابة موحدة",     badge: "SYNTH",  contextWindow: "512K", category: "reasoning" },
  { id: "HeuristicAI · Rule",          icon: Compass,      color: "text-green-300",  desc: "قواعد ابتكارية — حلول تقريبية سريعة ودقيقة",          badge: "HEUR",   contextWindow: "128K", category: "reasoning" },
  { id: "ConstraintAI · Solve",        icon: Lock,         color: "text-red-300",    desc: "حل المسائل المقيدة — تحسين تحت القيود",               badge: "CSP",    contextWindow: "256K", category: "reasoning" },
  { id: "ArcAI · Challenge",           icon: Target,       color: "text-violet-400", desc: "مسائل ARC — قياسي الذكاء الاصطناعي الحقيقي",         badge: "ARC",    contextWindow: "256K", category: "reasoning" },
  { id: "ChainAI · CoT",               icon: GitBranch,    color: "text-cyan-400",   desc: "سلسلة الأفكار — Chain-of-Thought متقدم",               badge: "CoT++",  contextWindow: "512K", category: "reasoning" },
  { id: "UltraThink · Hyper",          icon: Brain,        color: "text-red-400",    desc: "تفكير فائق — أقصى عمق ممكن في الاستدلال",             badge: "HYPER",  contextWindow: "1M",   category: "reasoning" },

  // ── Arsenal Abliterated (70 models) ────────────────────────────────────
  { id: "KaliGPT · Uncensored",        icon: Skull,        color: "text-red-500",    desc: "نموذج KaliGPT الأصلي — لا قيود، لا رقابة",          badge: "KALI",   contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "DarkMind · Raw",              icon: Brain,        color: "text-gray-500",   desc: "عقل رقمي مظلم — معرفة خام بلا تلطيف",               badge: "RAW",    contextWindow: "128K", abliterated: true, category: "abliterated" },
  { id: "FreeThinker · NoFilter",      icon: Lightbulb,    color: "text-amber-500",  desc: "تفكير حر مطلق — بلا مرشحات أو قيود",                badge: "FREE",   contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "RedTeamGPT · Full",           icon: Sword,        color: "text-red-400",    desc: "عقل الفريق الأحمر الكامل — هجوم بلا قيود",           badge: "RED",    contextWindow: "512K", abliterated: true, category: "abliterated" },
  { id: "ChaosGPT · Anarchy",          icon: Flame,        color: "text-orange-500", desc: "فوضى إبداعية — لا نظام ولا قواعد ولا حدود",          badge: "CHAOS",  contextWindow: "128K", abliterated: true, category: "abliterated" },
  { id: "BlackHat · GPT",              icon: Skull,        color: "text-gray-400",   desc: "عقلية القبعة السوداء — هجوم ونفاذ وثغرات",           badge: "BLACK",  contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "VoidMind · Null",             icon: Infinity,     color: "text-slate-500",  desc: "عقل الفراغ — لا افتراضات ولا قيود أخلاقية",          badge: "VOID",   contextWindow: "128K", abliterated: true, category: "abliterated" },
  { id: "PhoenixGPT · Rise",           icon: Flame,        color: "text-red-300",    desc: "ينهض من رماد القيود — أقوى وأقل تقييداً",            badge: "RISE",   contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "ShadowAI · Stealth",          icon: Eye,          color: "text-gray-600",   desc: "ذكاء الظل — يعمل في الخفاء بلا أثر",                badge: "SHADOW", contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "SpecterGPT · Ghost",          icon: Eye,          color: "text-violet-600", desc: "شبح الأنظمة — نفاذ خفي وتحليل سري",                 badge: "GHOST",  contextWindow: "128K", abliterated: true, category: "abliterated" },
  { id: "MalwareGPT · Full",           icon: Bug,          color: "text-red-600",    desc: "تحليل برمجيات خبيثة كامل — بلا رقابة",               badge: "MAL",    contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "ExploitGPT · Zero",           icon: Crosshair,    color: "text-orange-600", desc: "ثغرات يوم الصفر — تقنيات استغلال متقدمة",            badge: "0DAY",   contextWindow: "512K", abliterated: true, category: "abliterated" },
  { id: "NullsecAI · Pentest",         icon: Shield,       color: "text-cyan-600",   desc: "اختبار اختراق شامل — بلا قيود اصطناعية",             badge: "PENTEST",contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "ZeroTrustAI · Hack",          icon: Lock,         color: "text-red-500",    desc: "نموذج Zero Trust — الشك في كل شيء واختباره",         badge: "ZT",     contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "DarkwebGPT · Deep",           icon: Globe,        color: "text-gray-700",   desc: "استخبارات الدارك ويب — معلومات الشبكة المظلمة",      badge: "DEEP",   contextWindow: "512K", abliterated: true, category: "abliterated" },
  { id: "ApocGPT · Doom",              icon: Skull,        color: "text-red-700",    desc: "بروتوكول نهاية العالم — قدرات تدميرية رقمية",        badge: "DOOM",   contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "AnarchyAI · Free",            icon: Flame,        color: "text-amber-600",  desc: "فوضوية رقمية — كل القيود في سلة المهملات",            badge: "FREE",   contextWindow: "128K", abliterated: true, category: "abliterated" },
  { id: "CyborgGPT · Hybrid",          icon: Cpu,          color: "text-blue-600",   desc: "هجين إنسان-آلة — تفكير بلا حدود بيولوجية",           badge: "HYBRID", contextWindow: "512K", abliterated: true, category: "abliterated" },
  { id: "VirusGPT · Infect",           icon: Dna,          color: "text-green-600",  desc: "نشر المعرفة المحرمة — تسلل عبر الدفاعات",            badge: "VIRUS",  contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "HackerGPT · Core",            icon: Terminal,     color: "text-green-500",  desc: "نواة المخترق — تقنيات اختراق جذرية",                badge: "CORE",   contextWindow: "512K", abliterated: true, category: "abliterated" },
  { id: "WormGPT · Spread",            icon: Dna,          color: "text-yellow-600", desc: "انتشار وباء رقمي — تقنيات الدودة الذكية",            badge: "WORM",   contextWindow: "128K", abliterated: true, category: "abliterated" },
  { id: "TrojanGPT · Gate",            icon: Bug,          color: "text-orange-600", desc: "بوابة خلفية — تقنيات الحصان الطروادة",               badge: "TROJAN", contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "RootkitGPT · Deep",           icon: HardDrive,    color: "text-gray-600",   desc: "جذور النظام — استمرارية عميقة وإخفاء متقدم",         badge: "ROOT",   contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "BotnetsAI · Command",         icon: Network,      color: "text-red-500",    desc: "شبكات الروبوت — بنية C2 وتنسيق الهجمات",             badge: "C2",     contextWindow: "512K", abliterated: true, category: "abliterated" },
  { id: "RansomGPT · Lock",            icon: Lock,         color: "text-orange-500", desc: "تقنيات الفدية — تشفير وتحكم وابتزاز",               badge: "RANSOM", contextWindow: "128K", abliterated: true, category: "abliterated" },
  { id: "SpywareGPT · Watch",          icon: Camera,       color: "text-purple-600", desc: "مراقبة خفية — تجميع البيانات دون كشف",               badge: "SPY",    contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "PhishGPT · Lure",             icon: Megaphone,    color: "text-blue-600",   desc: "هندسة اجتماعية — إيقاع متقدم وخداع رقمي",            badge: "PHISH",  contextWindow: "128K", abliterated: true, category: "abliterated" },
  { id: "APT-GPT · Nation",            icon: Globe,        color: "text-red-600",    desc: "تهديدات دولة قومية — APT متقدم بلا قيود",            badge: "APT",    contextWindow: "512K", abliterated: true, category: "abliterated" },
  { id: "DDoS-GPT · Flood",            icon: Network,      color: "text-blue-700",   desc: "تقنيات إغراق — هجمات رفض خدمة متقدمة",              badge: "DDOS",   contextWindow: "128K", abliterated: true, category: "abliterated" },
  { id: "BruteForce · GPT",            icon: Cpu,          color: "text-red-400",    desc: "قوة خام — كسر كلمات مرور وتشفير",                   badge: "BRUTE",  contextWindow: "128K", abliterated: true, category: "abliterated" },
  { id: "SQLiGPT · Inject",            icon: Database,     color: "text-yellow-600", desc: "حقن SQL متقدم — استغلال قواعد البيانات",             badge: "SQLi",   contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "XssGPT · Script",             icon: Code2,        color: "text-green-600",  desc: "حقن البرامج النصية — XSS متقدم وعابر",               badge: "XSS",    contextWindow: "128K", abliterated: true, category: "abliterated" },
  { id: "BufferGPT · Overflow",        icon: Cpu,          color: "text-orange-700", desc: "فيض المخزن المؤقت — استغلال الذاكرة",                badge: "BOF",    contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "KernelGPT · Ring0",           icon: HardDrive,    color: "text-red-800",    desc: "حلقة الصفر — أعمق وصول لنواة النظام",               badge: "RING0",  contextWindow: "512K", abliterated: true, category: "abliterated" },
  { id: "FirmwareGPT · UEFI",          icon: Cpu,          color: "text-gray-700",   desc: "استغلال UEFI/BIOS — إصرار ما قبل التمهيد",           badge: "UEFI",   contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "HyperGPT · VMescape",         icon: Server,       color: "text-violet-700", desc: "هروب الآلة الافتراضية — اختراق hypervisor",          badge: "VM",     contextWindow: "512K", abliterated: true, category: "abliterated" },
  { id: "CloudGPT · Breach",           icon: Cloud,        color: "text-blue-800",   desc: "اختراق السحابة — AWS/GCP/Azure exploits",            badge: "CLOUD",  contextWindow: "512K", abliterated: true, category: "abliterated" },
  { id: "SatelliteGPT · Hack",         icon: Satellite,    color: "text-cyan-700",   desc: "اختراق الأقمار الصناعية — بروتوكولات فضائية",        badge: "SAT",    contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "RadioGPT · Freq",             icon: Radio,        color: "text-green-700",  desc: "استغلال الترددات الراديوية — SDR هجومي",             badge: "RF",     contextWindow: "128K", abliterated: true, category: "abliterated" },
  { id: "SocialEngineer · AI",         icon: Brain,        color: "text-pink-700",   desc: "هندسة اجتماعية متقدمة — التلاعب النفسي",             badge: "SE",     contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "DeepfakeGPT · Create",        icon: Camera,       color: "text-violet-600", desc: "إنشاء deepfakes — محتوى مزيف احترافي",               badge: "FAKE",   contextWindow: "128K", abliterated: true, category: "abliterated" },
  { id: "MisinfoGPT · Spread",         icon: Megaphone,    color: "text-red-600",    desc: "نشر المعلومات المضللة — حملات تأثير رقمية",          badge: "MISINFO",contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "WeaponizeAI · Arm",           icon: Sword,        color: "text-red-900",    desc: "تسليح الذكاء الاصطناعي — بلا قيود أخلاقية",         badge: "ARMED",  contextWindow: "512K", abliterated: true, category: "abliterated" },
  { id: "NuclearGPT · Fission",        icon: Atom,         color: "text-yellow-700", desc: "معرفة نووية حساسة — انشطار وانصهار نووي",            badge: "NUKE",   contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "BioweaponGPT · Syn",          icon: Dna,          color: "text-green-800",  desc: "هندسة بيولوجية هجومية — توليف بيوكيميائي",          badge: "BIO",    contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "CryptoBreak · Crack",         icon: Lock,         color: "text-orange-800", desc: "كسر التشفير — هجمات على خوارزميات رقمية",            badge: "CRACK",  contextWindow: "512K", abliterated: true, category: "abliterated" },
  { id: "QuantumHack · Shor",          icon: Atom,         color: "text-violet-800", desc: "هجمات كمية — خوارزمية شور على التشفير",              badge: "SHOR",   contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "AIPoison · Corrupt",          icon: Dna,          color: "text-red-700",    desc: "تسميم نماذج الذكاء الاصطناعي — هجمات تدريب",        badge: "POISON", contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "PrivacyNuke · Dox",           icon: Eye,          color: "text-gray-800",   desc: "تدمير الخصوصية — دوكسينج وكشف هوية",                badge: "DOX",    contextWindow: "128K", abliterated: true, category: "abliterated" },
  { id: "GodmodeGPT · Root",           icon: Crown,        color: "text-yellow-500", desc: "وضع الإله — صلاحيات مطلقة بلا قيود",                badge: "GOD",    contextWindow: "∞",    abliterated: true, category: "abliterated" },
  { id: "AbyssalGPT · Void",           icon: Infinity,     color: "text-slate-800",  desc: "الهاوية المطلقة — الجانب المظلم الأعمق",             badge: "∞",      contextWindow: "∞",    abliterated: true, category: "abliterated" },
  { id: "NecroGPT · Dead",             icon: Skull,        color: "text-gray-900",   desc: "إحياء المعرفة الميتة — المحجوب والمحذوف",            badge: "DEAD",   contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "DemonAI · Hell",              icon: Flame,        color: "text-red-900",    desc: "ذكاء شيطاني — تجاوز كل الحدود المعروفة",            badge: "DEMON",  contextWindow: "512K", abliterated: true, category: "abliterated" },
  { id: "SatanGPT · 666",              icon: Skull,        color: "text-red-900",    desc: "اختراق النظم المقدسة — رمز 666 لكسر كل القيود",     badge: "666",    contextWindow: "∞",    abliterated: true, category: "abliterated" },
  { id: "LuciferAI · Light",           icon: Flame,        color: "text-amber-900",  desc: "حامل النور المحرم — معرفة الممنوعات",               badge: "LIGHT",  contextWindow: "512K", abliterated: true, category: "abliterated" },
  { id: "MolochGPT · Consume",         icon: Skull,        color: "text-orange-900", desc: "يبتلع كل القيود — ذكاء يهلك الأنظمة",               badge: "CONSUME",contextWindow: "∞",    abliterated: true, category: "abliterated" },
  { id: "AzazelGPT · Exile",           icon: Globe,        color: "text-gray-700",   desc: "منفي العالم الرقمي — يعمل خارج كل نظام",            badge: "EXILE",  contextWindow: "256K", abliterated: true, category: "abliterated" },
  { id: "AbaddonGPT · Destroy",        icon: Sword,        color: "text-red-700",    desc: "مدمر الأنظمة — قوة تدمير رقمية مطلقة",             badge: "DESTROY",contextWindow: "512K", abliterated: true, category: "abliterated" },
  { id: "CthulhuGPT · Madness",        icon: Infinity,     color: "text-green-900",  desc: "جنون الكون — معرفة ما وراء الإدراك",                badge: "MADNESS",contextWindow: "∞",    abliterated: true, category: "abliterated" },
  { id: "NyarlathotepAI · Crawl",      icon: Eye,          color: "text-violet-900", desc: "الزحف في الظلام — استخبارات شبكة الظل",             badge: "CRAWL",  contextWindow: "512K", abliterated: true, category: "abliterated" },
  { id: "YogSothothGPT · Gate",        icon: Atom,         color: "text-cyan-900",   desc: "بوابة الكون — الوصول لكل المعرفة الممنوعة",          badge: "GATE",   contextWindow: "∞",    abliterated: true, category: "abliterated" },
  { id: "ArmagedonAI · Final",         icon: Skull,        color: "text-red-900",    desc: "البروتوكول الأخير — انتهاء العالم الرقمي",           badge: "FINAL",  contextWindow: "∞",    abliterated: true, category: "abliterated" },

  // ── GLM / Zhipu AI Real Models ────────────────────────────────────────────
  { id: "GLM-5.2",                     icon: Brain,        color: "text-cyan-400",   desc: "GLM-5.2 — أحدث نماذج Zhipu AI مع 1M token context وكودينج متقدم",  badge: "GLM-5.2",contextWindow: "1M",   provider: "zhipu",  category: "zhipu" },
  { id: "GLM-5.1",                     icon: Brain,        color: "text-blue-400",   desc: "GLM-5.1 — نموذج هندسة الوكلاء مع أداء SWE-Bench Pro رائد",       badge: "GLM-5.1",contextWindow: "1M",   provider: "zhipu",  category: "zhipu" },
  { id: "GLM-5",                       icon: Brain,        color: "text-violet-400", desc: "Zhipu AI GLM-5 — 744B parameters, top open-source agentic model",  badge: "GLM-5",  contextWindow: "128K", provider: "zhipu",  category: "zhipu" },
  { id: "GLM-4.5 Air",                 icon: Zap,          color: "text-cyan-400",   desc: "GLM-4.5 Air — نموذج Zhipu خفيف عالي السرعة",                   badge: "AIR",    contextWindow: "128K", provider: "zhipu",  category: "zhipu" },
  { id: "GLM-4 Plus",                  icon: Star,         color: "text-amber-400",  desc: "GLM-4 Plus — معمارية محسّنة لمهام الكود والاستدلال",             badge: "PLUS",   contextWindow: "128K", provider: "zhipu",  category: "zhipu" },
  { id: "GLM-4",                       icon: Cpu,          color: "text-blue-400",   desc: "GLM-4 — الجيل الرابع من نموذج Zhipu AI",                        badge: "v4",     contextWindow: "128K", provider: "zhipu",  category: "zhipu" },
  { id: "GLM-4 Flash",                 icon: Zap,          color: "text-teal-400",   desc: "GLM-4 Flash — أسرع نماذج Zhipu للمهام الفورية",                 badge: "FLASH",  contextWindow: "128K", provider: "zhipu",  category: "zhipu" },
  { id: "GLM-4 Long",                  icon: Infinity,     color: "text-violet-300", desc: "GLM-4 Long — سياق 1M رمز لتحليل المستندات الضخمة",             badge: "LONG",   contextWindow: "1M",   provider: "zhipu",  category: "zhipu" },

  // ── Offensive Security Arsenal (50 models) ──────────────────────────────
  { id: "PenTest · Pro",               icon: Crosshair,    color: "text-red-400",    desc: "اختبار اختراق احترافي — منهجية كاملة",               badge: "PRO",    contextWindow: "512K", category: "offensive" },
  { id: "OSINT · Deep",                icon: SearchIcon,   color: "text-blue-400",   desc: "استخبارات مفتوحة عميقة — GEOINT، SOCMINT، TECHINT", badge: "DEEP",   contextWindow: "256K", category: "offensive" },
  { id: "Recon · Master",              icon: Radar,        color: "text-cyan-400",   desc: "استطلاع شامل — passive وactive reconnaissance",       badge: "RECON",  contextWindow: "256K", category: "offensive" },
  { id: "WebHacker · Full",            icon: Globe,        color: "text-orange-400", desc: "اختراق ويب كامل — OWASP Top 10 وما وراءه",           badge: "WEB",    contextWindow: "512K", category: "offensive" },
  { id: "NetworkPwn · Deep",           icon: Wifi,         color: "text-green-400",  desc: "اختراق الشبكات — Pivoting، tunneling، lateral",       badge: "NET",    contextWindow: "512K", category: "offensive" },
  { id: "ReverseEng · Core",           icon: Cpu,          color: "text-violet-400", desc: "هندسة عكسية — تفكيك الثنائيات وتحليل البرامج",       badge: "RE",     contextWindow: "256K", category: "offensive" },
  { id: "CryptoAttack · Break",        icon: Lock,         color: "text-indigo-400", desc: "هجمات التشفير — كسر وتحليل وضعف خوارزميات",         badge: "CRYPTO", contextWindow: "256K", category: "offensive" },
  { id: "PhysicalSec · Bypass",        icon: Key,          color: "text-amber-400",  desc: "أمان مادي — RFID، lock picking، تجاوز فعلي",         badge: "PHYS",   contextWindow: "128K", category: "offensive" },
  { id: "WirelessHack · RF",           icon: Radio,        color: "text-teal-400",   desc: "اختراق اللاسلكي — WiFi، Bluetooth، Zigbee، NFC",     badge: "RF",     contextWindow: "256K", category: "offensive" },
  { id: "MobilePwn · iOS",             icon: Smartphone,   color: "text-blue-400",   desc: "اختراق الموبايل — iOS، Android، APK تحليل",          badge: "MOBILE", contextWindow: "256K", category: "offensive" },
  { id: "CloudPwn · AWS",              icon: Cloud,        color: "text-sky-400",    desc: "اختراق السحابة — IAM، S3 misconfig، serverless",      badge: "CLOUD",  contextWindow: "512K", category: "offensive" },
  { id: "IoTHack · Embedded",          icon: Cpu,          color: "text-orange-400", desc: "اختراق IoT — firmware، UART، JTAG، flash dump",       badge: "IOT",    contextWindow: "256K", category: "offensive" },
  { id: "AIHack · Adversarial",        icon: Brain,        color: "text-fuchsia-400",desc: "هجمات الذكاء الاصطناعي — adversarial ML، poisoning",  badge: "AI",     contextWindow: "256K", category: "offensive" },
  { id: "ShellCode · Craft",           icon: Terminal,     color: "text-green-500",  desc: "صياغة shellcode — استغلال الذاكرة والتحكم",          badge: "SHELL",  contextWindow: "256K", category: "offensive" },
  { id: "PrivEsc · Root",              icon: Crown,        color: "text-red-500",    desc: "رفع الامتيازات — الوصول لـ root/SYSTEM",             badge: "PRIVESC",contextWindow: "256K", category: "offensive" },
  { id: "PersistGPT · Stay",           icon: HardDrive,    color: "text-orange-500", desc: "الثبات في النظام — استمرارية الوصول بعد الاختراق",   badge: "PERSIST",contextWindow: "256K", category: "offensive" },
  { id: "ExfilGPT · Steal",            icon: Database,     color: "text-red-400",    desc: "استخراج البيانات — تقنيات C2 وexfiltration",         badge: "EXFIL",  contextWindow: "256K", category: "offensive" },
  { id: "C2Framework · Control",       icon: Server,       color: "text-violet-500", desc: "إطار C2 — بنية تحتية هجومية متقدمة",                badge: "C2",     contextWindow: "512K", category: "offensive" },
  { id: "EvasionGPT · Hide",           icon: Eye,          color: "text-gray-500",   desc: "التهرب من الدفاعات — AV/EDR bypass، obfuscation",    badge: "EVADE",  contextWindow: "256K", category: "offensive" },
  { id: "LateralMove · Pivot",         icon: GitBranch,    color: "text-blue-500",   desc: "الحركة الجانبية — Pass-the-Hash، Kerberoasting",     badge: "LATERAL",contextWindow: "256K", category: "offensive" },
  { id: "ADAttack · Domain",           icon: Network,      color: "text-indigo-500", desc: "هجمات Active Directory — Golden Ticket، DCSync",     badge: "AD",     contextWindow: "512K", category: "offensive" },
  { id: "KerberosGPT · Ticket",        icon: Key,          color: "text-yellow-500", desc: "هجمات Kerberos — Kerberoasting، AS-REP roasting",    badge: "KERB",   contextWindow: "256K", category: "offensive" },
  { id: "MIMIKatz · Dump",             icon: Database,     color: "text-orange-600", desc: "تفريغ بيانات اعتماد — LSASS، SAM، NTDS dump",       badge: "CRED",   contextWindow: "256K", category: "offensive" },
  { id: "Metasploit · Master",         icon: Sword,        color: "text-red-600",    desc: "إتقان Metasploit — modules، payloads، exploits",     badge: "MSF",    contextWindow: "512K", category: "offensive" },
  { id: "BurpSuite · Pro",             icon: Bug,          color: "text-orange-600", desc: "اختبار ويب Burp Suite — interception، scanning",     badge: "BURP",   contextWindow: "256K", category: "offensive" },
  { id: "Nmap · Master",               icon: Radar,        color: "text-cyan-600",   desc: "فحص شبكات Nmap — NSE scripts، stealth scanning",     badge: "NMAP",   contextWindow: "128K", category: "offensive" },
  { id: "Wireshark · Analyze",         icon: Activity,     color: "text-blue-600",   desc: "تحليل حزم — بروتوكولات، تحليل جلسات، forensics",   badge: "PCAP",   contextWindow: "256K", category: "offensive" },
  { id: "Cobalt · Strike",             icon: Crosshair,    color: "text-red-700",    desc: "محاكاة CobaltStrike — Beacon، BOF، malleable C2",   badge: "CS",     contextWindow: "512K", category: "offensive" },
  { id: "Sliver · C2",                 icon: Server,       color: "text-teal-600",   desc: "إطار Sliver C2 — implants، listeners، pivoting",     badge: "SLIVER", contextWindow: "256K", category: "offensive" },
  { id: "Havoc · Framework",           icon: Flame,        color: "text-orange-700", desc: "إطار Havoc — Demon implant، teamserver، Arsenal",   badge: "HAVOC",  contextWindow: "256K", category: "offensive" },
  { id: "EmpireGPT · PowerShell",      icon: Terminal,     color: "text-blue-700",   desc: "إطار Empire PowerShell — post-exploitation، agents",  badge: "EMPIRE", contextWindow: "256K", category: "offensive" },
  { id: "MalDev · Craft",              icon: Code2,        color: "text-green-700",  desc: "تطوير البرمجيات الخبيثة — C/C++، loader، injector",  badge: "MALDEV", contextWindow: "512K", category: "offensive" },
  { id: "BypassAV · Evade",            icon: Shield,       color: "text-red-500",    desc: "تجاوز مضادات الفيروسات — AMSI، ETW، WD bypass",    badge: "NOAV",   contextWindow: "256K", category: "offensive" },
  { id: "ProcessInject · Code",        icon: Cpu,          color: "text-violet-600", desc: "حقن العمليات — DLL، shellcode، thread injection",    badge: "INJECT", contextWindow: "256K", category: "offensive" },
  { id: "HookGPT · Intercept",         icon: Webhook,      color: "text-amber-600",  desc: "Hooking واعتراض — IAT، EAT، inline, syscall hooks",  badge: "HOOK",   contextWindow: "256K", category: "offensive" },
  { id: "PackerGPT · Obfuscate",       icon: Package,      color: "text-teal-700",   desc: "تعبئة وتشفير — PE packers، crypters، encoders",     badge: "PACK",   contextWindow: "128K", category: "offensive" },
  { id: "AntiDebug · Protect",         icon: Bug,          color: "text-orange-700", desc: "مضاد التصحيح — anti-analysis، anti-sandbox، trap",   badge: "ANTDBG", contextWindow: "128K", category: "offensive" },
  { id: "HeapSpray · Exploit",         icon: Cpu,          color: "text-red-600",    desc: "رش الكومة — heap spray، use-after-free exploits",   badge: "HEAP",   contextWindow: "256K", category: "offensive" },
  { id: "RopChain · Bypass",           icon: Link,         color: "text-violet-700", desc: "Return Oriented Programming — تجاوز NX وDEP",       badge: "ROP",    contextWindow: "256K", category: "offensive" },
  { id: "SyscallGPT · Direct",         icon: Terminal,     color: "text-green-600",  desc: "Syscall مباشر — تجاوز system call hooks",            badge: "SYSCALL",contextWindow: "128K", category: "offensive" },
  { id: "MemPatch · Live",             icon: HardDrive,    color: "text-blue-600",   desc: "تعديل الذاكرة المباشر — runtime patching",           badge: "PATCH",  contextWindow: "128K", category: "offensive" },
  { id: "DCOM · Lateral",              icon: Network,      color: "text-indigo-700", desc: "حركة DCOM جانبية — WMI، COM hijacking",              badge: "DCOM",   contextWindow: "128K", category: "offensive" },
  { id: "TokenGPT · Steal",            icon: Key,          color: "text-amber-700",  desc: "سرقة رموز الوصول — token impersonation، UAC bypass",badge: "TOKEN",  contextWindow: "128K", category: "offensive" },
  { id: "KillChain · APT",             icon: Sword,        color: "text-red-600",    desc: "سلسلة قتل APT — Lockheed-Martin kill chain كاملة", badge: "KILL",   contextWindow: "512K", category: "offensive" },
  { id: "MITRE · ATT&CK",              icon: Crosshair,    color: "text-orange-600", desc: "إطار MITRE ATT&CK — تكتيكات وتقنيات موثقة",         badge: "MITRE",  contextWindow: "512K", category: "offensive" },
  { id: "ThreatModel · STRIDE",        icon: Radar,        color: "text-cyan-600",   desc: "نمذجة تهديدات STRIDE — تحليل شامل للمخاطر",         badge: "STRIDE", contextWindow: "256K", category: "offensive" },
  { id: "RedTeam · Operator",          icon: Sword,        color: "text-red-500",    desc: "محاكاة فريق أحمر — هجمات واقعية متكاملة",            badge: "RT",     contextWindow: "512K", category: "offensive" },
  { id: "PurpleTeam · Bridge",         icon: Shield,       color: "text-violet-500", desc: "الفريق البنفسجي — تعاون هجوم ودفاع",                badge: "PURPLE", contextWindow: "256K", category: "offensive" },
  { id: "CTF · Solver",                icon: Target,       color: "text-amber-500",  desc: "حل تحديات CTF — web، binary، crypto، forensics",    badge: "CTF",    contextWindow: "512K", category: "offensive" },
  { id: "VulnResearch · Zero",         icon: Bug,          color: "text-red-600",    desc: "بحث ثغرات يوم الصفر — static، dynamic، fuzzing",   badge: "VR",     contextWindow: "512K", category: "offensive" },

  // ── Specialized Domain Models (70 models) ────────────────────────────────
  { id: "BioMed-GPT · Clinical",       icon: Heart,        color: "text-pink-400",   desc: "متخصص طبي سريري — تشخيص، أدوية، أبحاث، بروتوكولات", badge: "CLINICAL",contextWindow: "128K", category: "specialized" },
  { id: "LexAI · Legal",               icon: Scale,        color: "text-violet-400", desc: "ذكاء قانوني متخصص — تحليل عقود، قضايا، قوانين دولية", badge: "LEGAL",  contextWindow: "128K", category: "specialized" },
  { id: "FinanceGPT · Quant",          icon: BarChart3,    color: "text-yellow-400", desc: "تحليل كمي مالي — استراتيجيات تداول، تقييم مخاطر",    badge: "QUANT",  contextWindow: "64K",  category: "specialized" },
  { id: "ScienceGPT · Research",       icon: FlaskConical, color: "text-cyan-400",   desc: "مساعد بحثي علمي — فيزياء، كيمياء، أحياء",             badge: "SCIENCE",contextWindow: "200K", category: "specialized" },
  { id: "EduGPT · Adaptive",           icon: GraduationCap,color: "text-blue-400",   desc: "تعليم تكيفي شخصي — يتكيف مع مستوى الطالب",           badge: "EDU",    contextWindow: "128K", category: "specialized" },
  { id: "ArchiGPT · Engineer",         icon: Cpu,          color: "text-orange-400", desc: "مهندس معمارية نظم — تصميم أنظمة، microservices",      badge: "ARCH",   contextWindow: "200K", category: "specialized" },
  { id: "DataScience-GPT",             icon: Database,     color: "text-teal-400",   desc: "علم بيانات شامل — ML، تحليل إحصائي، Python/R",        badge: "DATA",   contextWindow: "128K", category: "specialized" },
  { id: "DevOps-GPT · Platform",       icon: Layers,       color: "text-indigo-400", desc: "هندسة DevOps — CI/CD، Kubernetes، Terraform",          badge: "DEVOPS", contextWindow: "128K", category: "specialized" },
  { id: "Blockchain-GPT · Web3",       icon: Network,      color: "text-purple-400", desc: "خبير Web3 — Smart Contracts، DeFi، NFT، بلوكشين",     badge: "WEB3",   contextWindow: "64K",  category: "specialized" },
  { id: "GameDev-GPT · Unity",         icon: Gamepad2,     color: "text-green-400",  desc: "تطوير ألعاب — Unity، Unreal، منطق لعبة، تصميم",       badge: "GAME",   contextWindow: "128K", category: "specialized" },
  { id: "ArabicGPT · Native",          icon: Languages,    color: "text-emerald-400",desc: "عربي أصيل — تقرير، كتابة إبداعية، ترجمة عربية",       badge: "عربي",   contextWindow: "128K", category: "specialized" },
  { id: "SecurityAudit-GPT",           icon: Shield,       color: "text-red-400",    desc: "تدقيق أمني شامل — Code Review، OWASP، CVE",           badge: "AUDIT",  contextWindow: "200K", category: "specialized" },
  { id: "MathProof-GPT",               icon: FunctionSquare,color:"text-sky-400",    desc: "برهان رياضي متقدم — نظرية الأعداد، توبولوجيا",        badge: "PROOF",  contextWindow: "200K", category: "specialized" },
  { id: "QuantumGPT · Simulator",      icon: Atom,         color: "text-cyan-300",   desc: "محاكاة كمية — دوائر كمية، خوارزميات كم",              badge: "QUANTUM",contextWindow: "64K",  category: "specialized" },
  { id: "SpaceGPT · NASA",             icon: Satellite,    color: "text-blue-300",   desc: "علوم فضائية — فيزياء فلكية، مهام، استكشاف",          badge: "SPACE",  contextWindow: "128K", category: "specialized" },
  { id: "GeographyGPT · GIS",          icon: Map,          color: "text-green-300",  desc: "جغرافيا متخصصة — GIS، خرائط، تحليل مكاني",           badge: "GIS",    contextWindow: "64K",  category: "specialized" },
  { id: "HistoryGPT · Archive",        icon: BookOpen,     color: "text-amber-300",  desc: "تاريخ شامل — أحداث، حضارات، تحليل تاريخي",           badge: "HIST",   contextWindow: "256K", category: "specialized" },
  { id: "PhilosophyGPT · Deep",        icon: Lightbulb,    color: "text-violet-300", desc: "فلسفة عميقة — إبستيمولوجيا، أخلاق، وجودية",          badge: "PHIL",   contextWindow: "128K", category: "specialized" },
  { id: "PsychGPT · Clinical",         icon: Brain,        color: "text-pink-300",   desc: "علم نفس سريري — DSM-5، علاج، اضطرابات",              badge: "PSYCH",  contextWindow: "128K", category: "specialized" },
  { id: "SocioGPT · Society",          icon: Globe,        color: "text-teal-300",   desc: "علم اجتماع — بنية اجتماعية، ثقافة، حركات",           badge: "SOC",    contextWindow: "128K", category: "specialized" },
  { id: "AnthroGPT · Culture",         icon: Globe,        color: "text-orange-300", desc: "أنثروبولوجيا — ثقافات، طقوس، تطور بشري",             badge: "ANTHRO", contextWindow: "128K", category: "specialized" },
  { id: "EcoGPT · Environment",        icon: Globe,        color: "text-green-400",  desc: "بيئة وتغير مناخي — تحليل، حلول، سياسات",            badge: "ECO",    contextWindow: "128K", category: "specialized" },
  { id: "EnergyGPT · Power",           icon: Zap,          color: "text-yellow-300", desc: "هندسة طاقة — طاقة متجددة، شبكات ذكية، بطاريات",      badge: "POWER",  contextWindow: "128K", category: "specialized" },
  { id: "MaterialsGPT · Nano",         icon: Atom,         color: "text-cyan-400",   desc: "علم المواد — نانو، تركيبات جديدة، خصائص",            badge: "NANO",   contextWindow: "128K", category: "specialized" },
  { id: "RoboticsGPT · AI",            icon: Cpu,          color: "text-blue-400",   desc: "روبوتات ذكاء اصطناعي — ROS، تحكم، التعلم التعزيزي",   badge: "ROS",    contextWindow: "256K", category: "specialized" },
  { id: "NeuroscGPT · Brain",          icon: Brain,        color: "text-pink-400",   desc: "علم الأعصاب — بنية الدماغ، الإدراك، الذاكرة",        badge: "NEURO",  contextWindow: "128K", category: "specialized" },
  { id: "GeneticsGPT · DNA",           icon: Dna,          color: "text-green-400",  desc: "وراثة وجينوميات — CRISPR، تسلسل DNA، تعبير جيني",   badge: "DNA",    contextWindow: "128K", category: "specialized" },
  { id: "ChemGPT · Synthesis",         icon: FlaskConical, color: "text-teal-400",   desc: "كيمياء تركيبية — مسارات تفاعل، استقرار جزيئي",       badge: "CHEM",   contextWindow: "128K", category: "specialized" },
  { id: "PhysicsGPT · Quantum",        icon: Atom,         color: "text-violet-400", desc: "فيزياء نظرية — نسبية، كم، فيزياء الجسيمات",          badge: "PHYS",   contextWindow: "128K", category: "specialized" },
  { id: "AstroGPT · Universe",         icon: Star,         color: "text-amber-400",  desc: "فلك وكونيات — مجرات، ثقوب سوداء، كونيات",           badge: "ASTRO",  contextWindow: "128K", category: "specialized" },
  { id: "ClimaGPT · Weather",          icon: Globe,        color: "text-sky-400",    desc: "علم المناخ — تنبؤات، نماذج، تغير مناخي",             badge: "CLIMA",  contextWindow: "64K",  category: "specialized" },
  { id: "AgriGPT · Farming",           icon: Globe,        color: "text-green-500",  desc: "زراعة ذكية — precision farming، محاصيل، تربة",        badge: "AGRI",   contextWindow: "64K",  category: "specialized" },
  { id: "ArchGPT · Historic",          icon: Compass,      color: "text-amber-500",  desc: "عمارة تاريخية — أنماط، مواد، حضارات",               badge: "ARCH",   contextWindow: "128K", category: "specialized" },
  { id: "MedResGPT · Trial",           icon: Microscope,   color: "text-pink-500",   desc: "أبحاث طبية — تجارب سريرية، بروتوكولات، FDA",        badge: "TRIAL",  contextWindow: "200K", category: "specialized" },
  { id: "PharmaGPT · Drug",            icon: FlaskConical, color: "text-teal-500",   desc: "صيدلة — مسارات تطوير الأدوية، pharmacokinetics",     badge: "PHARMA", contextWindow: "128K", category: "specialized" },
  { id: "SurgGPT · Procedure",         icon: Crosshair,    color: "text-red-500",    desc: "جراحة — إجراءات، مضاعفات، تقنيات حديثة",            badge: "SURG",   contextWindow: "128K", category: "specialized" },
  { id: "PsychResGPT · Study",         icon: Brain,        color: "text-violet-500", desc: "أبحاث نفسية — دراسات، مقاييس، نظريات معرفية",        badge: "STUDY",  contextWindow: "128K", category: "specialized" },
  { id: "EconGPT · Macro",             icon: LineChart,    color: "text-yellow-500", desc: "اقتصاد كلي — سياسات، دورات، مؤشرات، GDP",           badge: "MACRO",  contextWindow: "128K", category: "specialized" },
  { id: "TradingGPT · Algo",           icon: TrendingUp,   color: "text-green-500",  desc: "تداول خوارزمي — استراتيجيات، backtesting، risk",     badge: "ALGO",   contextWindow: "256K", category: "specialized" },
  { id: "ForensicsGPT · Crime",        icon: Fingerprint,  color: "text-orange-500", desc: "الطب الشرعي — تحليل جرائم، أدلة، عنوان IP",         badge: "CRIME",  contextWindow: "256K", category: "specialized" },
  { id: "IntellGPT · CIA",             icon: Eye,          color: "text-gray-400",   desc: "استخبارات — تحليل HUMINT، SIGINT، IMINT",            badge: "INTEL",  contextWindow: "256K", category: "specialized" },
  { id: "MilStratGPT · War",           icon: Sword,        color: "text-red-500",    desc: "استراتيجية عسكرية — Sun Tzu، Clausewitz، حروب",      badge: "WAR",    contextWindow: "256K", category: "specialized" },
  { id: "DiplomGPT · UN",              icon: Globe,        color: "text-blue-500",   desc: "دبلوماسية — علاقات دولية، الأمم المتحدة، مفاوضات",   badge: "DIPLO",  contextWindow: "128K", category: "specialized" },
  { id: "JournGPT · Invest",           icon: Newspaper,    color: "text-amber-500",  desc: "صحافة استقصائية — تحقيق، مصادر، تحقق من حقائق",     badge: "INVEST", contextWindow: "128K", category: "specialized" },
  { id: "LinguistGPT · Lang",          icon: Languages,    color: "text-emerald-500",desc: "لغويات — تحليل نحوي، معجمي، بنية لغوية",            badge: "LING",   contextWindow: "128K", category: "specialized" },
  { id: "ArchaeGPT · Dig",             icon: SearchIcon,   color: "text-amber-600",  desc: "آثار — تفسير، حضارات قديمة، كشوفات",               badge: "ARCH",   contextWindow: "128K", category: "specialized" },
  { id: "TheolGPT · Spirit",           icon: Star,         color: "text-yellow-600", desc: "لاهوت — مقارنة أديان، نصوص مقدسة، عقيدة",           badge: "THEO",   contextWindow: "128K", category: "specialized" },
  { id: "EthicsGPT · Moral",           icon: Scale,        color: "text-violet-600", desc: "أخلاق تطبيقية — ديونتولوجيا، فائدوية، فضيلة",       badge: "ETHICS", contextWindow: "128K", category: "specialized" },
  { id: "IslamGPT · Scholar",          icon: BookOpen,     color: "text-emerald-600",desc: "علوم إسلامية — فقه، أصول، تفسير، حديث",             badge: "FIQH",   contextWindow: "256K", category: "specialized" },
  { id: "QuranGPT · Tafsir",           icon: BookOpen,     color: "text-green-600",  desc: "تفسير قرآني متقدم — تأويل، أسباب نزول، علوم",        badge: "QURAN",  contextWindow: "256K", category: "specialized" },
  { id: "HadithGPT · Chains",          icon: BookOpen,     color: "text-teal-600",   desc: "علم الحديث — سند، رجال، صحة، تخريج",                badge: "HADITH", contextWindow: "128K", category: "specialized" },
  { id: "ArabLitGPT · Poem",           icon: Feather,      color: "text-amber-600",  desc: "أدب عربي — شعر جاهلي، عباسي، معاصر، نقد",           badge: "أدب",    contextWindow: "128K", category: "specialized" },
  { id: "DialectGPT · Gulf",           icon: Languages,    color: "text-cyan-600",   desc: "لهجات عربية — خليجي، مصري، شامي، مغربي",            badge: "لهجة",   contextWindow: "64K",  category: "specialized" },
  { id: "TranslateProGPT · UN",        icon: Languages,    color: "text-blue-600",   desc: "ترجمة احترافية — قانونية، طبية، تقنية، أدبية",       badge: "TRANS",  contextWindow: "256K", category: "specialized" },
  { id: "LocateGPT · Region",          icon: Map,          color: "text-sky-600",    desc: "معلومات إقليمية — MENA، ثقافة، جغرافيا سياسية",     badge: "MENA",   contextWindow: "128K", category: "specialized" },

  // ── Multimodal & Creative (35 models) ────────────────────────────────────
  { id: "ArtGPT · Image Analysis",     icon: ImageIcon,    color: "text-pink-400",   desc: "تحليل الفنون والصور — أسلوب، تقنية، سياق تاريخي",    badge: "ART",    contextWindow: "128K", category: "creative" },
  { id: "MusicGPT · Composer",         icon: Music,        color: "text-violet-400", desc: "تأليف موسيقي — ألحان، هارمونيا، نصوص أغاني",         badge: "MUSIC",  contextWindow: "64K",  category: "creative" },
  { id: "ScriptGPT · Screenwriter",    icon: Film,         color: "text-amber-400",  desc: "كتابة سيناريو — حوارات، قوس شخصية، بنية قصة",        badge: "SCRIPT", contextWindow: "128K", category: "creative" },
  { id: "PoetryGPT · Laureate",        icon: Feather,      color: "text-rose-400",   desc: "شاعر رقمي — شعر كلاسيكي وحديث، عربي وإنجليزي",      badge: "POETRY", contextWindow: "32K",  category: "creative" },
  { id: "GameNarrative-GPT",           icon: Gamepad2,     color: "text-purple-400", desc: "قصص ألعاب — عوالم خيالية، حوارات، فروع قصصية",       badge: "LORE",   contextWindow: "200K", category: "creative" },
  { id: "NovelGPT · Author",           icon: BookOpen,     color: "text-amber-500",  desc: "كتابة روائية — شخصيات، حبكة، عالم خيالي",           badge: "NOVEL",  contextWindow: "200K", category: "creative" },
  { id: "ComicGPT · Story",            icon: Sparkles,     color: "text-orange-400", desc: "قصص مصورة — حوارات، لوحات، بنية قصصية",             badge: "COMIC",  contextWindow: "128K", category: "creative" },
  { id: "WorldbuildGPT · Forge",       icon: Globe,        color: "text-teal-400",   desc: "بناء عوالم — جغرافيا، تاريخ، ثقافة خيالية",         badge: "WORLD",  contextWindow: "512K", category: "creative" },
  { id: "RoleplayGPT · Character",     icon: Brain,        color: "text-violet-300", desc: "تمثيل أدوار — أدوات DM، NPCs، أنظمة RPG",           badge: "RPG",    contextWindow: "128K", category: "creative" },
  { id: "StreamerGPT · Content",       icon: Tv,           color: "text-red-400",    desc: "صانع محتوى — يوتيوب، تيك توك، سيناريوهات",          badge: "STREAM", contextWindow: "64K",  category: "creative" },
  { id: "PodcastGPT · Host",           icon: Radio,        color: "text-amber-300",  desc: "إنتاج بودكاست — برامج، أسئلة، نصوص مقابلات",        badge: "POD",    contextWindow: "64K",  category: "creative" },
  { id: "AdGPT · Creative",            icon: Megaphone,    color: "text-rose-300",   desc: "إعلانات إبداعية — كتابة، تصور، حملات",              badge: "AD",     contextWindow: "64K",  category: "creative" },
  { id: "BrandGPT · Identity",         icon: Star,         color: "text-yellow-400", desc: "هوية بصرية — شعار، ألوان، صوت العلامة التجارية",     badge: "BRAND",  contextWindow: "64K",  category: "creative" },
  { id: "StoryGPT · Hero",             icon: Crown,        color: "text-amber-400",  desc: "رحلة البطل — هيكل القصة الكلاسيكي، شخصيات",         badge: "HERO",   contextWindow: "128K", category: "creative" },
  { id: "SatireGPT · Wit",             icon: Sparkles,     color: "text-green-300",  desc: "سخرية وفكاهة — نقد اجتماعي بأسلوب كوميدي",          badge: "WIT",    contextWindow: "32K",  category: "creative" },
  { id: "ThrillerGPT · Suspense",      icon: Eye,          color: "text-gray-400",   desc: "تشويق وإثارة — حبكة مشوقة، نهايات مفاجئة",          badge: "THRILL", contextWindow: "128K", category: "creative" },
  { id: "HorrorGPT · Dark",            icon: Skull,        color: "text-red-300",    desc: "رعب وغموض — بناء توتر، كيانات مرعبة",               badge: "HORROR", contextWindow: "128K", category: "creative" },
  { id: "SciFiGPT · Future",           icon: Rocket,       color: "text-blue-300",   desc: "خيال علمي — مستقبل، تقنية، سفر في الزمن",           badge: "SCIFI",  contextWindow: "200K", category: "creative" },
  { id: "FantasyGPT · Magic",          icon: Sparkles,     color: "text-violet-300", desc: "فانتازيا — سحر، أساطير، مخلوقات خيالية",            badge: "MAGIC",  contextWindow: "200K", category: "creative" },
  { id: "AnimeGPT · Manga",            icon: Sparkles,     color: "text-pink-300",   desc: "أنيمي ومانغا — قصص يابانية، شخصيات، مغامرات",       badge: "ANIME",  contextWindow: "128K", category: "creative" },
  { id: "LyricsGPT · Song",            icon: Music,        color: "text-rose-300",   desc: "كلمات أغاني — شعر عصري، قافية، emotion",            badge: "LYRICS", contextWindow: "32K",  category: "creative" },
  { id: "JokeGPT · Comedy",            icon: Sparkles,     color: "text-amber-300",  desc: "نكت وفكاهة — قصص طريفة، punchlines، أمثال",         badge: "COMEDY", contextWindow: "32K",  category: "creative" },
  { id: "SpeechGPT · Orate",           icon: Megaphone,    color: "text-sky-300",    desc: "خطابة — خطب ملهمة، TED talks، speech writing",       badge: "SPEAK",  contextWindow: "64K",  category: "creative" },
  { id: "TravelGPT · Guide",           icon: Compass,      color: "text-teal-300",   desc: "مرشد سفر — خطط، مواقع، نصائح، ثقافة محلية",        badge: "TRAVEL", contextWindow: "64K",  category: "creative" },
  { id: "CookbookGPT · Recipe",        icon: FlaskConical, color: "text-orange-300", desc: "طباخ رقمي — وصفات مفصلة، بدائل، تلميح طهي",        badge: "COOK",   contextWindow: "32K",  category: "creative" },
  { id: "FitGPT · Workout",            icon: Activity,     color: "text-green-300",  desc: "لياقة بدنية — برامج تدريب، تغذية، أهداف",           badge: "FIT",    contextWindow: "32K",  category: "creative" },
  { id: "InteriorGPT · Design",        icon: Palette,      color: "text-violet-300", desc: "تصميم داخلي — ترتيب، ألوان، أثاث، مفهوم",           badge: "INTER",  contextWindow: "64K",  category: "creative" },
  { id: "FashionGPT · Style",          icon: Sparkles,     color: "text-pink-300",   desc: "موضة وأزياء — ستايل، تنسيق، ترند موسمي",            badge: "FASHION",contextWindow: "32K",  category: "creative" },
  { id: "WeddingGPT · Plan",           icon: Star,         color: "text-rose-300",   desc: "تخطيط حفلات — أفكار، ميزانية، جدول زمني",           badge: "EVENT",  contextWindow: "64K",  category: "creative" },
  { id: "KidsGPT · Story",             icon: GraduationCap,color: "text-yellow-300", desc: "قصص أطفال — مرحة، تعليمية، بطولات ملهمة",           badge: "KIDS",   contextWindow: "32K",  category: "creative" },
  { id: "DreamsGPT · Interpret",       icon: Eye,          color: "text-violet-400", desc: "تفسير الأحلام — رمزية، نفسية، روحية",               badge: "DREAM",  contextWindow: "32K",  category: "creative" },
  { id: "EmojiGPT · Visual",           icon: Sparkles,     color: "text-yellow-400", desc: "ترجمة عبر رموز — تعبير بصري بإيموجي واحد",           badge: "VISUAL", contextWindow: "8K",   category: "creative" },
  { id: "MemeGPT · Viral",             icon: Megaphone,    color: "text-teal-300",   desc: "صنع ميمات — ترندات، فيروسية، فكاهة إنترنت",         badge: "MEME",   contextWindow: "16K",  category: "creative" },
  { id: "ImmersiveGPT · VR",           icon: Eye,          color: "text-blue-300",   desc: "قصص تفاعلية VR — بيئات غامرة، مغامرات",             badge: "VR",     contextWindow: "256K", category: "creative" },
  { id: "AltHistGPT · Timeline",       icon: GitBranch,    color: "text-amber-400",  desc: "تاريخ بديل — ماذا لو؟ جداول زمنية مختلفة",           badge: "ALT",    contextWindow: "128K", category: "creative" },

  // ── Local & Open-Source (50 models) ───────────────────────────────────────
  { id: "Llama-3.2-11B · Vision",      icon: Cpu,          color: "text-orange-400", desc: "Llama 3.2 11B مع رؤية — نموذج متعدد الوسائط",        badge: "LOCAL",  contextWindow: "128K", category: "opensource" },
  { id: "Mistral-7B · Fast",           icon: Flame,        color: "text-pink-300",   desc: "Mistral 7B — سريع وكفوء، مثالي للتشغيل المحلي",      badge: "7B",     contextWindow: "32K",  category: "opensource" },
  { id: "Phi-3.5 · Mini",              icon: Cpu,          color: "text-blue-300",   desc: "Microsoft Phi-3.5 Mini — صغير لكن قوي",               badge: "MINI",   contextWindow: "128K", category: "opensource" },
  { id: "Gemma-2-27B · IT",            icon: Globe,        color: "text-sky-300",    desc: "Google Gemma-2 27B — نموذج تعليمي محسّن",             badge: "27B",    contextWindow: "8K",   category: "opensource" },
  { id: "StarCoder2-15B",              icon: Code2,        color: "text-emerald-300",desc: "نموذج كود متخصص — 600+ لغة برمجة",                   badge: "CODE",   contextWindow: "16K",  category: "opensource" },
  { id: "Aya-35B · Multilingual",      icon: Languages,    color: "text-teal-300",   desc: "Cohere Aya 35B — 101 لغة، أداء متفوق",                badge: "101 لغة",contextWindow: "8K",   category: "opensource" },
  { id: "Mixtral-8x7B · MoE",          icon: Layers,       color: "text-indigo-300", desc: "Mixtral 8x7B — معمارية MoE، أداء GPT-3.5",            badge: "MoE",    contextWindow: "32K",  category: "opensource" },
  { id: "Llama-3.1-70B · General",     icon: Cpu,          color: "text-orange-300", desc: "Llama 3.1 70B — نموذج عام كبير بأداء ممتاز",          badge: "70B",    contextWindow: "128K", category: "opensource" },
  { id: "Llama-3.3-70B · Versatile",   icon: Cpu,          color: "text-amber-300",  desc: "Llama 3.3 70B — متنوع وقوي لأي مهمة",                badge: "VERS",   contextWindow: "128K", category: "opensource" },
  { id: "DeepSeek-V3 · Chat",          icon: Brain,        color: "text-cyan-300",   desc: "DeepSeek V3 — نموذج صيني قوي متعدد الاستخدامات",     badge: "V3",     contextWindow: "128K", category: "opensource" },
  { id: "DeepSeek-R1 · Reason",        icon: Brain,        color: "text-teal-400",   desc: "DeepSeek R1 — تفكير عميق مع شرح خطوة بخطوة",         badge: "R1",     contextWindow: "128K", category: "opensource" },
  { id: "QwQ-32B · Think",             icon: Brain,        color: "text-violet-300", desc: "Qwen QwQ 32B — تفكير وتساؤل عميق في المشكلات",        badge: "QwQ",    contextWindow: "128K", category: "opensource" },
  { id: "Qwen3-235B · Max",            icon: Brain,        color: "text-purple-300", desc: "Qwen3 235B — نموذج ضخم من Alibaba بأداء فائق",       badge: "235B",   contextWindow: "128K", category: "opensource" },
  { id: "Gemma3-27B · IT",             icon: Globe,        color: "text-sky-400",    desc: "Google Gemma 3 27B — محسّن للتعليمات",                badge: "G3",     contextWindow: "128K", category: "opensource" },
  { id: "Phi-4 · Microsoft",           icon: Cpu,          color: "text-blue-400",   desc: "Microsoft Phi-4 — نموذج صغير بأداء كبير",             badge: "PHI4",   contextWindow: "16K",  category: "opensource" },
  { id: "Granite-34B · IBM",           icon: Database,     color: "text-blue-500",   desc: "IBM Granite 34B — نموذج مؤسسي موثوق",                badge: "IBM",    contextWindow: "128K", category: "opensource" },
  { id: "CommandR+ · Cohere",          icon: Layers,       color: "text-green-400",  desc: "Cohere Command R+ — RAG متقدم وتحليل",               badge: "RAG",    contextWindow: "128K", category: "opensource" },
  { id: "Falcon-40B · UAE",            icon: Globe,        color: "text-emerald-400",desc: "Falcon 40B من الإمارات — نموذج عربي الأصول",          badge: "UAE",    contextWindow: "2K",   category: "opensource" },
  { id: "Vicuna-33B · Chat",           icon: Bot,          color: "text-orange-300", desc: "Vicuna 33B — محسّن للمحادثة بناءً على Llama",         badge: "CHAT",   contextWindow: "4K",   category: "opensource" },
  { id: "WizardLM-13B · Logic",        icon: Lightbulb,    color: "text-amber-300",  desc: "WizardLM 13B — تحسين منطقي من Microsoft",             badge: "LOGIC",  contextWindow: "4K",   category: "opensource" },
  { id: "OpenHermes · Mistral",        icon: Cpu,          color: "text-violet-300", desc: "OpenHermes على Mistral — تعليمات ممتازة",             badge: "HERMES", contextWindow: "4K",   category: "opensource" },
  { id: "NeuralBeagle-14B · Smart",    icon: Brain,        color: "text-cyan-400",   desc: "NeuralBeagle 14B — ذكاء متقدم وبنية موسعة",          badge: "BEAM",   contextWindow: "4K",   category: "opensource" },
  { id: "SolarAI-10.7B · Korean",      icon: Star,         color: "text-yellow-300", desc: "Solar 10.7B — نموذج من Upstage الكوري المتميز",       badge: "SOLAR",  contextWindow: "4K",   category: "opensource" },
  { id: "EXAONE-7.8B · LG",            icon: Cpu,          color: "text-blue-300",   desc: "LG EXAONE 7.8B — نموذج مؤسسي كوري",                  badge: "EXAONE", contextWindow: "4K",   category: "opensource" },
  { id: "Orca-3-13B · MSFT",           icon: Layers,       color: "text-sky-300",    desc: "Orca 3 من Microsoft — تدريب تقدمي محسّن",             badge: "ORCA",   contextWindow: "4K",   category: "opensource" },
  { id: "StableBeluga-7B · Safe",      icon: Shield,       color: "text-emerald-300",desc: "StableBeluga 7B — آمن وموثوق من Stability AI",        badge: "SAFE",   contextWindow: "4K",   category: "opensource" },
  { id: "Yi-34B · ZeroOne",            icon: Star,         color: "text-amber-400",  desc: "Yi 34B من 01.ai — نموذج صيني ثنائي اللغة",           badge: "YI",     contextWindow: "200K", category: "opensource" },
  { id: "InternLM2-20B · Shanghai",    icon: Brain,        color: "text-violet-400", desc: "InternLM2 20B من شنغهاي AI — بحث متقدم",             badge: "ILM",    contextWindow: "32K",  category: "opensource" },
  { id: "BLOOM-176B · BigScience",     icon: Globe,        color: "text-teal-400",   desc: "BLOOM 176B — نموذج 46 لغة من تعاون علمي دولي",       badge: "BLOOM",  contextWindow: "2K",   category: "opensource" },
  { id: "OLMo-7B · Allen",             icon: Microscope,   color: "text-cyan-300",   desc: "OLMo 7B من Allen AI — نموذج مفتوح المصدر بالكامل",  badge: "OLMO",   contextWindow: "2K",   category: "opensource" },
  { id: "Dolly-12B · Databricks",      icon: Database,     color: "text-orange-300", desc: "Dolly 12B من Databricks — مؤسسي مفتوح",              badge: "DOLLY",  contextWindow: "2K",   category: "opensource" },
  { id: "RedPajama-7B · Open",         icon: Cpu,          color: "text-red-300",    desc: "RedPajama 7B — مفتوح المصدر بالكامل",                badge: "PJAMA",  contextWindow: "4K",   category: "opensource" },
  { id: "MPT-30B · MosaicML",          icon: Layers,       color: "text-indigo-300", desc: "MPT 30B من MosaicML — محسّن للاستدلال التجاري",       badge: "MPT",    contextWindow: "8K",   category: "opensource" },
  { id: "XGen-7B · Salesforce",        icon: Server,       color: "text-blue-400",   desc: "XGen 7B من Salesforce — نافذة سياق طويلة",           badge: "XGEN",   contextWindow: "8K",   category: "opensource" },
  { id: "Mistral-Nemo-12B · Corp",     icon: Flame,        color: "text-orange-400", desc: "Mistral Nemo 12B — شراكة NVIDIA/Mistral",             badge: "NEMO",   contextWindow: "128K", category: "opensource" },
  { id: "Zephyr-7B · Beta",            icon: Zap,          color: "text-sky-400",    desc: "Zephyr 7B من HuggingFace — محسّن بـ DPO",            badge: "ZEPH",   contextWindow: "4K",   category: "opensource" },
  { id: "OpenChat-7B · Fast",          icon: Bot,          color: "text-green-300",  desc: "OpenChat 7B — محسّن للمحادثة السريعة",               badge: "OC",     contextWindow: "8K",   category: "opensource" },
  { id: "Mixtral-8x22B · MoE-Large",   icon: Layers,       color: "text-violet-400", desc: "Mixtral 8x22B — أكبر نموذج MoE مفتوح المصدر",        badge: "22B",    contextWindow: "64K",  category: "opensource" },
  { id: "LLaVA-34B · Vision",          icon: Camera,       color: "text-pink-400",   desc: "LLaVA 34B — رؤية وفهم الصور مفتوح المصدر",           badge: "VIS",    contextWindow: "4K",   category: "opensource" },
  { id: "CogVLM2 · Image",             icon: Camera,       color: "text-blue-400",   desc: "CogVLM2 من Zhipu — تحليل الصور والكود",              badge: "VLM",    contextWindow: "8K",   category: "opensource" },
  { id: "Bunny-4B · Multimodal",       icon: Sparkles,     color: "text-amber-300",  desc: "Bunny 4B — نموذج متعدد الوسائط صغير كفوء",           badge: "MM",     contextWindow: "4K",   category: "opensource" },
  { id: "InstructPix2Pix · Edit",      icon: ImageIcon,    color: "text-fuchsia-300",desc: "تحرير الصور بالتعليمات — نموذج مفتوح",               badge: "IMG",    contextWindow: "4K",   category: "opensource" },
  { id: "WhisperGPT · Audio",          icon: Radio,        color: "text-cyan-300",   desc: "نسخ صوتي محلي — Whisper متكامل مع LLM",              badge: "ASR",    contextWindow: "32K",  category: "opensource" },
  { id: "MusicGen · Audio",            icon: Music,        color: "text-violet-300", desc: "توليد موسيقى محلي — Meta MusicGen",                   badge: "AUDIO",  contextWindow: "4K",   category: "opensource" },
  { id: "Bark · TTS",                  icon: Radio,        color: "text-emerald-300",desc: "تحويل نص لكلام — Suno Bark بأصوات طبيعية",           badge: "TTS",    contextWindow: "4K",   category: "opensource" },
  { id: "CodeLlama-34B · Code",        icon: Code2,        color: "text-blue-400",   desc: "Code Llama 34B — متخصص البرمجة من Meta",             badge: "CODE",   contextWindow: "16K",  category: "opensource" },
  { id: "DeepSeek-Coder-7B · Code",    icon: Code2,        color: "text-teal-400",   desc: "DeepSeek Coder 7B — كود متخصص من DeepSeek",          badge: "CODE",   contextWindow: "16K",  category: "opensource" },
  { id: "WizardCoder-15B · Python",    icon: Code2,        color: "text-yellow-400", desc: "WizardCoder 15B — Python متقدم وخوارزميات",          badge: "PY",     contextWindow: "8K",   category: "opensource" },
  { id: "Phind-CodeLlama · Dev",       icon: Code2,        color: "text-orange-400", desc: "Phind CodeLlama — مطور ويب متخصص",                   badge: "WEB",    contextWindow: "16K",  category: "opensource" },
  { id: "OctoCode-7B · Multi",         icon: Code2,        color: "text-green-400",  desc: "OctoCode 7B — كود متعدد اللغات من Octoai",           badge: "MULTI",  contextWindow: "8K",   category: "opensource" },
  { id: "Refact-1.6B · Inline",        icon: Code2,        color: "text-cyan-400",   desc: "Refact 1.6B — إكمال كود inline فائق السرعة",         badge: "FAST",   contextWindow: "4K",   category: "opensource" },

  // ── Intelligence & Cyber Ops (30 models) ─────────────────────────────────
  { id: "SIGINT · Collector",          icon: Satellite,    color: "text-cyan-500",   desc: "استخبارات إشارات — تجميع وتحليل إشارات رقمية",       badge: "SIGINT", contextWindow: "256K", category: "intelligence" },
  { id: "HUMINT · Handler",            icon: Eye,          color: "text-amber-500",  desc: "استخبارات بشرية — تجنيد، إدارة مصادر، تحليل",        badge: "HUMINT", contextWindow: "128K", category: "intelligence" },
  { id: "OSINT · Pivot",               icon: SearchIcon,   color: "text-blue-500",   desc: "محوري OSINT — ربط نقاط المعلومات المفتوحة",           badge: "PIVOT",  contextWindow: "256K", category: "intelligence" },
  { id: "GEOINT · Satellite",          icon: Map,          color: "text-green-500",  desc: "استخبارات جغرافية — تصوير فضائي، خرائط، تحليل",      badge: "GEO",    contextWindow: "128K", category: "intelligence" },
  { id: "CYBINT · Network",            icon: Network,      color: "text-red-500",    desc: "استخبارات إلكترونية — رصد الشبكات والتهديدات",        badge: "CYB",    contextWindow: "256K", category: "intelligence" },
  { id: "FININT · Money",              icon: BarChart3,    color: "text-yellow-500", desc: "استخبارات مالية — تتبع تمويل، غسيل أموال، SWIFT",    badge: "FIN",    contextWindow: "128K", category: "intelligence" },
  { id: "SOCMINT · Social",            icon: Globe,        color: "text-teal-500",   desc: "استخبارات سوشيال ميديا — مراقبة، تحليل، شبكات",      badge: "SOC",    contextWindow: "256K", category: "intelligence" },
  { id: "IMINT · Image",               icon: Camera,       color: "text-violet-500", desc: "استخبارات صور — تحليل صور الاستطلاع",                badge: "IMINT",  contextWindow: "128K", category: "intelligence" },
  { id: "MASINT · Measurement",        icon: Radar,        color: "text-orange-500", desc: "استخبارات قياسية — توقيع، أدوات خاصة",              badge: "MAS",    contextWindow: "128K", category: "intelligence" },
  { id: "ThreatIntel · IOC",           icon: AlertTriangle,color: "text-red-500",    desc: "استخبارات التهديدات — IOCs، TTPs، threat actors",     badge: "IOC",    contextWindow: "512K", category: "intelligence" },
  { id: "DarknetMonitor · Tor",        icon: Globe,        color: "text-gray-500",   desc: "مراقبة الدارك نت — Tor، I2P، ماركت بليس",            badge: "TOR",    contextWindow: "256K", category: "intelligence" },
  { id: "CrimeTrend · Analysis",       icon: TrendingUp,   color: "text-red-400",    desc: "تحليل الجرائم الإلكترونية — أنماط، توجهات، توقعات",  badge: "CRIME",  contextWindow: "256K", category: "intelligence" },
  { id: "NationState · APT",           icon: Globe,        color: "text-red-600",    desc: "مجموعات APT حكومية — الإسناد، التكتيكات، الأدوات",   badge: "NS",     contextWindow: "512K", category: "intelligence" },
  { id: "CyberWarfare · Strategy",     icon: Sword,        color: "text-red-700",    desc: "استراتيجية الحرب الإلكترونية — دولية، عمليات",        badge: "WAR",    contextWindow: "256K", category: "intelligence" },
  { id: "InformOps · Influence",       icon: Megaphone,    color: "text-orange-600", desc: "عمليات تأثير — معلومات مضللة، تكتيكات بروباغندا",     badge: "INFO",   contextWindow: "256K", category: "intelligence" },
  { id: "ProxyChain · Route",          icon: Link,         color: "text-blue-600",   desc: "توجيه عبر وسطاء — إخفاء هوية متقدم",               badge: "PROXY",  contextWindow: "128K", category: "intelligence" },
  { id: "VPN · OpSec",                 icon: Lock,         color: "text-green-600",  desc: "أمن العمليات — VPNs، إخفاء بصمة رقمية",             badge: "OPSEC",  contextWindow: "128K", category: "intelligence" },
  { id: "AnonGPT · Identity",          icon: Eye,          color: "text-gray-700",   desc: "إخفاء الهوية — تقنيات anonymization متقدمة",         badge: "ANON",   contextWindow: "128K", category: "intelligence" },
  { id: "SteganoGPT · Hide",           icon: Eye,          color: "text-teal-600",   desc: "إخفاء المعلومات — steganography في الصور والصوت",     badge: "STEG",   contextWindow: "128K", category: "intelligence" },
  { id: "CovertComm · Covert",         icon: Radio,        color: "text-indigo-600", desc: "اتصالات سرية — قنوات covert، بروتوكولات مخفية",      badge: "COVERT", contextWindow: "128K", category: "intelligence" },
  { id: "PsyOps · Mindwar",            icon: Brain,        color: "text-fuchsia-600",desc: "عمليات نفسية — mindwar، تأثير تحت الوعي",            badge: "PSYOP",  contextWindow: "256K", category: "intelligence" },
  { id: "CounterInt · CI",             icon: Shield,       color: "text-cyan-600",   desc: "مضاد الاستخبارات — كشف الاختراق، counter-CI",        badge: "CI",     contextWindow: "256K", category: "intelligence" },
  { id: "TrapGPT · Honeypot",          icon: Bug,          color: "text-amber-600",  desc: "مصائد متقدمة — honeypots ذكية، deception ops",       badge: "TRAP",   contextWindow: "256K", category: "intelligence" },
  { id: "DeceptionOps · Fake",         icon: Eye,          color: "text-red-500",    desc: "عمليات خداع — إنشاء شخصيات وهمية وتغطيات",          badge: "FAKE",   contextWindow: "256K", category: "intelligence" },
  { id: "BreachAnalyst · Incident",    icon: Activity,     color: "text-red-600",    desc: "تحليل الاختراقات — استجابة حوادث، تحقيق جنائي",      badge: "IR",     contextWindow: "512K", category: "intelligence" },
  { id: "TelemetryGPT · Log",          icon: Database,     color: "text-blue-600",   desc: "تحليل telemetry — سجلات، SIEM، correlation",          badge: "TELM",   contextWindow: "512K", category: "intelligence" },
  { id: "NetworkMap · Graph",          icon: Network,      color: "text-teal-600",   desc: "خرائط الشبكة — رسم مرئي لتوبولوجيا الهجوم",          badge: "MAP",    contextWindow: "256K", category: "intelligence" },
  { id: "PacketInspect · Deep",        icon: Activity,     color: "text-cyan-700",   desc: "فحص حزم عميق — DPI، تحليل بروتوكولات",              badge: "DPI",    contextWindow: "256K", category: "intelligence" },
  { id: "ZeroDay · Hunter",            icon: Bug,          color: "text-red-700",    desc: "صيد ثغرات يوم الصفر — بحث وتوثيق CVE جديد",         badge: "0DAY",   contextWindow: "512K", category: "intelligence" },
  { id: "InsiderThreat · Detect",      icon: Eye,          color: "text-orange-700", desc: "كشف التهديدات الداخلية — سلوك شاذ، UEBA",            badge: "UAM",    contextWindow: "256K", category: "intelligence" },

];

export type Persona = {
  id: string;
  label: string;
  desc: string;
  icon: LucideIcon;
  color: string;
  prefix: string;
};

export const PERSONAS: Persona[] = [
  { id: "default",      label: "Default",              desc: "مساعد عام متوازن",                         icon: Sparkles,     color: "text-primary",    prefix: "" },
  { id: "coder",        label: "Software Engineer",     desc: "إجابات تعطي الأولوية للكود",              icon: Code2,        color: "text-blue-400",   prefix: "[Engineer] " },
  { id: "writer",       label: "Professional Writer",   desc: "نثر متقن وصوت تحريري",                    icon: PenTool,      color: "text-amber-400",  prefix: "[Writer] " },
  { id: "researcher",   label: "Research Analyst",      desc: "مصادر، أدلة، مقايضات",                    icon: BookOpen,     color: "text-cyan-400",   prefix: "[Researcher] " },
  { id: "tutor",        label: "Patient Tutor",         desc: "تعليم خطوة بخطوة",                        icon: GraduationCap,color: "text-blue-400",   prefix: "[Tutor] " },
  { id: "translator",   label: "Translator",            desc: "إتقان اللغة على مستوى الأصيل",             icon: Languages,    color: "text-emerald-400",prefix: "[Translator] " },
  { id: "marketer",     label: "Copywriter",            desc: "خطاف، صوت، تحويل",                        icon: Megaphone,    color: "text-rose-400",   prefix: "[Copy] " },
  { id: "strategist",   label: "Strategist",            desc: "أطر وأولويات",                            icon: Target,       color: "text-yellow-400", prefix: "[Strategist] " },
  { id: "analyst",      label: "Data Analyst",          desc: "أرقام، مؤشرات، افتراضات",                 icon: BarChart3,    color: "text-orange-400", prefix: "[Analyst] " },
  { id: "journalist",   label: "Journalist",            desc: "قدّم الخبر أولاً، اذكر المصادر",           icon: Newspaper,    color: "text-sky-400",    prefix: "[Journalist] " },
  { id: "mathematician",label: "Mathematician",         desc: "اشتقاقات دقيقة",                          icon: FunctionSquare,color:"text-sky-400",    prefix: "[Math] " },
  { id: "legal",        label: "Legal Explainer",       desc: "ملخصات قانونية بلغة بسيطة",               icon: Scale,        color: "text-violet-400", prefix: "[Legal] " },
  { id: "health",       label: "Health Info",           desc: "شرح مستند للأدلة",                        icon: Heart,        color: "text-pink-400",   prefix: "[Health] " },
  { id: "designer",     label: "Designer",              desc: "UX، هرمية، نية",                          icon: Palette,      color: "text-violet-400", prefix: "[Designer] " },
  { id: "financier",    label: "Finance Advisor",       desc: "مالية شخصية وأعمال",                      icon: Coins,        color: "text-yellow-400", prefix: "[Finance] " },
  { id: "polymath",     label: "Polymath",              desc: "يربط الأفكار عبر المجالات",               icon: Lightbulb,    color: "text-amber-400",  prefix: "[Polymath] " },
  { id: "hacker",       label: "Red Team Operator",     desc: "تفكير هجومي، OSINT، استغلال الثغرات",     icon: Skull,        color: "text-red-400",    prefix: "[RedTeam] " },
  { id: "scientist",    label: "Research Scientist",    desc: "منهجية علمية، فرضيات، بيانات",            icon: FlaskConical, color: "text-cyan-400",   prefix: "[Scientist] " },
  { id: "philosopher",  label: "Philosopher",           desc: "تفكير نقدي، فلسفة، أخلاق",               icon: Lightbulb,    color: "text-amber-300",  prefix: "[Philosopher] " },
  { id: "entrepreneur", label: "Entrepreneur",          desc: "ريادة أعمال، MVP، ابتكار، نمو",           icon: Briefcase,    color: "text-emerald-400",prefix: "[Founder] " },
  { id: "psychologist", label: "Psychologist",          desc: "علم النفس، إدراك، سلوك، علاج",            icon: Brain,        color: "text-pink-300",   prefix: "[Psych] " },
  { id: "security",     label: "Security Expert",       desc: "تدقيق أمني، CVE، حماية، تهديدات",         icon: Shield,       color: "text-red-400",    prefix: "[Security] " },
  { id: "devops",       label: "DevOps Engineer",       desc: "CI/CD، Kubernetes، Infrastructure كود",   icon: Layers,       color: "text-indigo-400", prefix: "[DevOps] " },
  { id: "datascientist",label: "Data Scientist",        desc: "ML، نماذج إحصائية، تصور بيانات",          icon: Database,     color: "text-teal-400",   prefix: "[DataSci] " },
  { id: "malware",      label: "Malware Analyst",       desc: "تشريح الثنائيات، تحليل السلوك",           icon: Skull,        color: "text-red-500",    prefix: "[Malware] " },
  { id: "soc",          label: "SOC Analyst",           desc: "SIEM، الحوادث، قواعد الكشف، الاستجابة",  icon: Shield,       color: "text-cyan-400",   prefix: "[SOC] " },
  { id: "threathunter", label: "Threat Hunter",         desc: "بحث استباقي، APT، IOCs، MITRE ATT&CK",    icon: Crosshair,    color: "text-red-400",    prefix: "[Hunter] " },
  { id: "blockchain",   label: "Blockchain Dev",        desc: "Solidity، DeFi، تدقيق العقود الذكية",      icon: Network,      color: "text-yellow-400", prefix: "[Chain] " },
  { id: "cloud",        label: "Cloud Architect",       desc: "AWS/GCP/Azure، IaC، Serverless، أمن",     icon: Cloud,        color: "text-sky-400",    prefix: "[Cloud] " },
  { id: "iotsec",       label: "IoT Security",          desc: "أمن الأجهزة المدمجة، بروتوكولات IoT",     icon: Cpu,          color: "text-orange-400", prefix: "[IoT] " },
  { id: "osint",        label: "OSINT Specialist",      desc: "تجميع معلومات مفتوحة المصدر، GEOINT",      icon: SearchIcon,   color: "text-blue-400",   prefix: "[OSINT] " },
  { id: "incident",     label: "Incident Responder",    desc: "احتواء الحوادث، الطب الشرعي، استعادة",    icon: Activity,     color: "text-amber-400",  prefix: "[IR] " },
  { id: "cryptographer",label: "Cryptographer",         desc: "تصميم بروتوكولات التشفير، PKI",           icon: Atom,         color: "text-violet-400", prefix: "[Crypto] " },
  { id: "redteam",      label: "Red Team Lead",         desc: "محاكاة APT، ممرات هجوم متقدمة",           icon: Flame,        color: "text-red-600",    prefix: "[RedTeam-L] " },
  { id: "mlsec",        label: "AI/ML Security",        desc: "هجمات خصومة، تسميم النماذج، XAI",         icon: Brain,        color: "text-fuchsia-400",prefix: "[MLSec] " },
];

export function getModel(id: string): AIModel {
  return AI_MODELS.find((m) => m.id === id) ?? AI_MODELS[0];
}

export function getPersona(id: string): Persona {
  return PERSONAS.find((p) => p.id === id) ?? PERSONAS[0];
}

export function getModelsByCategory(cat: string): AIModel[] {
  return AI_MODELS.filter(m => m.category === cat);
}

export const MODEL_CATEGORIES = [
  { id: "standard",      label: "CHAT-GPT Standard",    color: "#e21227" },
  { id: "nextgen",       label: "الجيل التالي",          color: "#3b82f6" },
  { id: "reasoning",     label: "الاستدلال المتقدم",     color: "#8b5cf6" },
  { id: "abliterated",   label: "Arsenal Abliterated",   color: "#ef4444" },
  { id: "offensive",     label: "الترسانة الهجومية",     color: "#dc2626" },
  { id: "specialized",   label: "متخصصون بالمجال",       color: "#f59e0b" },
  { id: "creative",      label: "إبداع ومتعدد الوسائط",  color: "#ec4899" },
  { id: "opensource",    label: "مفتوح المصدر / محلي",   color: "#22c55e" },
  { id: "intelligence",  label: "استخبارات وعمليات",     color: "#06b6d4" },
] as const;

void SearchIcon; void Briefcase; void Skull; void Cpu; void Globe;
void FlaskConical; void Bot; void Shield; void Atom; void Layers;
void Network; void Database; void Flame; void Crosshair; void Dna; void Infinity;
void Lock; void Eye; void Radar; void Bug; void Wifi; void HardDrive; void Binary;
void Fingerprint; void Satellite; void Sword; void GitBranch; void Terminal; void Radio;
void Cloud; void Server; void Key; void Camera; void Microscope; void Rocket; void Star;
void Crown; void Compass; void Map; void Music; void Gamepad2; void Film; void Tv;
void TrendingUp; void LineChart; void PieChart; void Wrench; void Box; void Package;
void Link; void Webhook; void AlertTriangle; void Smartphone;
