import { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Users, Play, Brain, Shield, Crosshair, Activity, Search } from "lucide-react";

interface Props { open: boolean; onOpenChange: (v: boolean) => void; }

interface Agent {
  id: string; name: string; role: string; color: string;
  icon: typeof Brain; status: "idle" | "running" | "done" | "error";
  logs: string[]; findings: number;
}

const buildAgents = (): Agent[] => [
  { id: "recon", name: "RECON AGENT", role: "Open-Source Intelligence & Discovery", color: "#00e5ff", icon: Search, status: "idle", logs: [], findings: 0 },
  { id: "exploit", name: "EXPLOIT AGENT", role: "Vulnerability Analysis & Exploitation", color: "#e21227", icon: Crosshair, status: "idle", logs: [], findings: 0 },
  { id: "analyst", name: "ANALYST AGENT", role: "Behavioral Analysis & Threat Intelligence", color: "#fbbf24", icon: Activity, status: "idle", logs: [], findings: 0 },
  { id: "defense", name: "DEFENSE AGENT", role: "Hardening Recommendations & Mitigation", color: "#4ade80", icon: Shield, status: "idle", logs: [], findings: 0 },
];

const AGENT_LOGS: Record<string, string[]> = {
  recon: [
    "[*] Starting OSINT recon...",
    "[>] Querying Shodan API...",
    "[+] 3 subdomains discovered",
    "[+] ASN: AS14618 (Amazon)",
    "[>] Enumerating social media...",
    "[+] 2 employee LinkedIn profiles found",
    "[>] Searching Pastebin/GitHub for leaked creds...",
    "[!] GitHub commit contains API key (leaked 2023-04-12)",
    "[+] Email pattern identified: firstname@company.com",
    "[>] Checking DNS records...",
    "[+] MX: Google Workspace, SPF: misconfigured (soft fail)",
    "[!] Recon phase complete — 14 intelligence items collected",
  ],
  exploit: [
    "[*] Initializing vulnerability scanner...",
    "[>] Running Nuclei templates (2,847 templates)...",
    "[!] CRITICAL: Apache 2.4.41 — CVE-2021-41773 path traversal",
    "[!] HIGH: MySQL 3306 exposed publicly",
    "[>] Testing SQLi in login form...",
    "[+] Time-based blind SQLi confirmed in username field",
    "[>] Attempting authentication bypass...",
    "[+] Admin panel accessible via ' OR 1=1-- -",
    "[>] Testing file upload endpoint...",
    "[!] PHP webshell upload successful",
    "[+] RCE via webshell: uid=33(www-data)",
    "[!] 4 critical vulns, 6 high, 12 medium identified",
  ],
  analyst: [
    "[*] Loading threat intelligence feeds...",
    "[>] Checking IOCs against VirusTotal...",
    "[+] No malicious hashes in uploaded files",
    "[>] Analyzing network traffic patterns...",
    "[!] Anomalous outbound traffic to known C2 IP (185.220.101.x)",
    "[>] Correlating with MITRE ATT&CK framework...",
    "[+] Tactics detected: TA0001, TA0002, TA0003, TA0011",
    "[>] Checking for lateral movement indicators...",
    "[!] Suspicious SMB activity — WannaCry-like lateral spread",
    "[>] Timeline reconstruction...",
    "[+] Initial access: 2024-01-15 03:42 UTC",
    "[!] Threat actor: Likely APT28 (confidence: 72%)",
  ],
  defense: [
    "[*] Generating hardening recommendations...",
    "[>] Analyzing current firewall rules...",
    "[+] Recommendation: Block MySQL port 3306 from internet",
    "[>] Checking patch status...",
    "[+] Recommendation: Patch Apache CVE-2021-41773 immediately",
    "[>] Reviewing authentication configuration...",
    "[+] Recommendation: Enable MFA on all admin accounts",
    "[>] Analyzing WAF configuration...",
    "[+] Recommendation: Add WAF rule for path traversal patterns",
    "[>] Checking backup integrity...",
    "[+] Recommendation: Air-gap critical backups",
    "[!] 18 hardening actions generated — priority ordered",
  ],
};

const SYNTHESIS_REPORT = `═══════════════════════════════════════════════════
MULTI-AGENT SOC SYNTHESIS REPORT
Generated by KaliGPT Neural Coordinator v3.0
═══════════════════════════════════════════════════

EXECUTIVE SUMMARY:
Target organization has critical security gaps across multiple attack surfaces. 
Full compromise achievable in under 30 minutes by a skilled threat actor.

CRITICAL FINDINGS (immediate action required):
1. Apache CVE-2021-41773 — unauthenticated RCE via path traversal
2. MySQL 3306 exposed to internet without authentication  
3. GitHub API key leak (active, not rotated since April 2023)
4. PHP webshell upload + execution confirmed

THREAT ACTOR ASSESSMENT:
- Likely APT28 (Fancy Bear / GRU) — 72% confidence
- C2 infrastructure matches known APT28 patterns
- Initial access vector: spear-phishing + 0-day

ATTACK TIMELINE:
03:42 UTC — Initial access via CVE-2021-41773
03:47 UTC — Privilege escalation to root
03:52 UTC — Lateral movement initiated
04:15 UTC — Domain controller hit

DEFENSE SCORE: 23/100 (CRITICAL)

TOP PRIORITY ACTIONS:
1. PATCH Apache immediately — 15 min fix
2. FIREWALL MySQL port — 5 min fix  
3. ROTATE leaked API keys — 10 min fix
4. ENABLE MFA everywhere — 30 min fix
5. SEGMENT network — 4 hours

═══════════════════════════════════════════════════`;

export function MultiAgentSOCModal({ open, onOpenChange }: Props) {
  const [target, setTarget] = useState("target.company.com");
  const [agents, setAgents] = useState<Agent[]>(buildAgents());
  const [running, setRunning] = useState(false);
  const [synthesis, setSynthesis] = useState("");
  const [showSynthesis, setShowSynthesis] = useState(false);
  const [selectedAgent, setSelectedAgent] = useState<Agent | null>(null);
  const timersRef = useRef<ReturnType<typeof setInterval>[]>([]);
  const synthRef = useRef<HTMLDivElement>(null);

  useEffect(() => { if (synthRef.current) synthRef.current.scrollTop = synthRef.current.scrollHeight; }, [synthesis]);

  function launch() {
    const fresh = buildAgents();
    setAgents(fresh); setRunning(true); setSynthesis(""); setShowSynthesis(false); setSelectedAgent(null);
    timersRef.current.forEach(clearInterval);
    timersRef.current = [];

    fresh.forEach((agent, agentIdx) => {
      const lines = AGENT_LOGS[agent.id];
      let lineIdx = 0;
      setAgents(prev => prev.map(a => a.id === agent.id ? { ...a, status: "running" } : a));
      const t = setInterval(() => {
        if (lineIdx >= lines.length) {
          clearInterval(t);
          setAgents(prev => prev.map(a => a.id === agent.id ? {
            ...a, status: "done",
            logs: lines, findings: Math.floor(Math.random() * 6) + 4
          } : a));
          if (agentIdx === 3) {
            setTimeout(() => {
              setRunning(false); setShowSynthesis(true);
              let si = 0;
              const st = setInterval(() => {
                setSynthesis(SYNTHESIS_REPORT.slice(0, si));
                si += 8;
                if (si >= SYNTHESIS_REPORT.length) clearInterval(st);
              }, 20);
            }, 800);
          }
          return;
        }
        setAgents(prev => prev.map(a => a.id === agent.id ? { ...a, logs: [...a.logs, lines[lineIdx]] } : a));
        lineIdx++;
      }, 400 + agentIdx * 150);
      timersRef.current.push(t);
    });
  }

  const active = selectedAgent ? agents.find(a => a.id === selectedAgent.id) ?? selectedAgent : null;

  if (!open) return null;
  return (
    <AnimatePresence>
      <motion.div className="fixed inset-0 z-50 flex items-center justify-center p-4"
        style={{ background: "rgba(0,0,0,0.92)" }}
        initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
        <motion.div className="relative w-full rounded-2xl overflow-hidden flex flex-col"
          style={{ maxWidth: 1300, maxHeight: "90vh", background: "#080808", border: "1px solid #1a1a1a" }}
          initial={{ scale: 0.95 }} animate={{ scale: 1 }}>

          <div className="flex items-center justify-between px-6 py-4 border-b" style={{ borderColor: "#141414" }}>
            <div className="flex items-center gap-3">
              <div className="w-9 h-9 rounded-xl flex items-center justify-center" style={{ background: "rgba(168,85,247,0.1)", border: "1px solid rgba(168,85,247,0.25)" }}>
                <Users className="w-5 h-5" style={{ color: "#a855f7" }} />
              </div>
              <div>
                <div className="text-sm font-bold tracking-widest" style={{ color: "#a855f7" }}>MULTI-AGENT SOC SYSTEM</div>
                <div className="text-xs font-mono mt-0.5" style={{ color: "#2a2a2a" }}>4 Parallel AI Agents · Neural Coordination · Synthesis Report</div>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <input value={target} onChange={e => setTarget(e.target.value)}
                className="px-3 py-1.5 rounded-lg text-xs font-mono bg-transparent outline-none"
                style={{ border: "1px solid #1a1a1a", color: "#888", width: 220 }} placeholder="Target domain / IP" />
              <motion.button onClick={launch} disabled={running} whileTap={{ scale: 0.97 }}
                className="flex items-center gap-2 px-4 py-1.5 rounded-xl text-xs font-bold tracking-widest"
                style={{ background: running ? "rgba(168,85,247,0.04)" : "rgba(168,85,247,0.12)", border: "1px solid rgba(168,85,247,0.35)", color: running ? "#333" : "#a855f7" }}>
                <Play className="w-3.5 h-3.5" />{running ? "AGENTS RUNNING..." : "DEPLOY ALL AGENTS"}
              </motion.button>
            </div>
            <button onClick={() => onOpenChange(false)} className="w-8 h-8 rounded-lg flex items-center justify-center hover:bg-white/5">
              <X className="w-4 h-4" style={{ color: "#666" }} />
            </button>
          </div>

          <div className="flex flex-1 overflow-hidden" style={{ minHeight: 0 }}>
            <div className="flex-1 flex flex-col overflow-hidden">
              <div className="grid grid-cols-2 gap-3 p-4 h-64">
                {agents.map(agent => {
                  const Icon = agent.icon;
                  const isSelected = active?.id === agent.id;
                  return (
                    <motion.button key={agent.id} onClick={() => setSelectedAgent(agents.find(a => a.id === agent.id) ?? null)}
                      className="flex flex-col p-3 rounded-xl text-left overflow-hidden relative"
                      style={{ background: isSelected ? `${agent.color}08` : "#0a0a0a", border: `1px solid ${isSelected ? agent.color + "33" : agent.status === "running" ? agent.color + "22" : "#111"}` }}>
                      <div className="flex items-center gap-2 mb-2">
                        <div className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0" style={{ background: `${agent.color}15`, border: `1px solid ${agent.color}33` }}>
                          <Icon className="w-3.5 h-3.5" style={{ color: agent.color }} />
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="text-[10px] font-bold" style={{ color: agent.color }}>{agent.name}</div>
                          <div className="text-[8px]" style={{ color: "#2a2a2a" }}>{agent.role}</div>
                        </div>
                        <div className="flex items-center gap-1.5 flex-shrink-0">
                          {agent.status === "running" && <motion.div className="w-2 h-2 rounded-full" style={{ background: agent.color }} animate={{ opacity: [1, 0] }} transition={{ repeat: Infinity, duration: 0.6 }} />}
                          {agent.status === "done" && <span className="text-[9px]" style={{ color: "#4ade80" }}>✓ DONE</span>}
                          {agent.status === "idle" && <span className="text-[9px]" style={{ color: "#1a1a1a" }}>IDLE</span>}
                          {agent.findings > 0 && <span className="px-1.5 py-0.5 rounded text-[8px] font-bold" style={{ background: `${agent.color}15`, color: agent.color }}>{agent.findings}</span>}
                        </div>
                      </div>
                      <div className="flex-1 overflow-hidden">
                        {agent.logs.slice(-3).map((l, i) => (
                          <div key={i} className="text-[8px] font-mono truncate" style={{ color: l.startsWith("[!]") ? agent.color : "#2a2a2a" }}>{l}</div>
                        ))}
                      </div>
                      {agent.status === "running" && (
                        <motion.div className="absolute bottom-0 left-0 h-0.5" style={{ background: agent.color }}
                          animate={{ width: ["0%", "100%"] }} transition={{ duration: 4, ease: "linear", repeat: Infinity }} />
                      )}
                    </motion.button>
                  );
                })}
              </div>

              {showSynthesis && (
                <div ref={synthRef} className="flex-1 overflow-y-auto p-4 mx-4 mb-4 rounded-xl font-mono text-[10px]"
                  style={{ background: "#030303", border: "1px solid rgba(168,85,247,0.15)", minHeight: 0 }}>
                  <pre style={{ color: "#a855f7", whiteSpace: "pre-wrap" }}>{synthesis}</pre>
                </div>
              )}
            </div>

            {active && (
              <motion.div className="w-72 border-l flex flex-col" style={{ borderColor: "#111" }} initial={{ width: 0, opacity: 0 }} animate={{ width: 288, opacity: 1 }}>
                <div className="p-3 border-b flex items-center gap-2" style={{ borderColor: "#111" }}>
                  <div className="w-1.5 h-1.5 rounded-full" style={{ background: active.color }} />
                  <span className="text-[10px] font-bold" style={{ color: active.color }}>{active.name}</span>
                </div>
                <div className="flex-1 overflow-y-auto p-3 space-y-0.5 font-mono text-[9px]" style={{ minHeight: 0 }}>
                  {active.logs.map((l, i) => (
                    <motion.div key={i} initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                      style={{ color: l.startsWith("[!]") ? active.color : l.startsWith("[+]") ? "#4ade80" : l.startsWith("[>]") ? "#00e5ff" : "#2a2a2a" }}>
                      {l}
                    </motion.div>
                  ))}
                </div>
              </motion.div>
            )}
          </div>
        </motion.div>
      </motion.div>
    </AnimatePresence>
  );
}
