apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mr7-ingress
  namespace: mr7ai
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mr7.ai
        - www.mr7.ai
      secretName: mr7-tls
  rules:
    - host: mr7.ai
      http:
        paths:
          - path: /api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: mr7-api-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mr7-frontend-svc
                port:
                  number: 80
    - host: www.mr7.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mr7-frontend-svc
                port:
                  number: 80
